import { Restaurant, RestaurantDetail } from '@/domains/restaurants/types';


// ─────────────────────────────────────────────
// REAL CANADIAN EVENTS MOCK DATA
// These are real recurring annual events in Canada.
// Fields match the Event type used in useEvents.ts:
// _id, name, title, category, description,
// imageUrl, images, date, startAt, endAt,
// venue, price, priceInfo, location
// ─────────────────────────────────────────────
export const mockEvents = [
    {
        _id: 'ev1',
        name: 'Toronto International Film Festival',
        title: 'Toronto International Film Festival',
        category: 'Film & Arts',
        description: 'One of the most prestigious film festivals in the world. TIFF brings together thousands of films, industry professionals, and movie lovers from across the globe to Toronto every September. World premieres, galas, and public screenings take place across downtown Toronto venues.',
        imageUrl:   'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwCiLh17MJaRxddacGHQdqPHel3svONlDELQ&s' ,
        images: [
                       'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxzXeRqMr1V9GHVvCace9diA6ow-Oh0MvOhA&s',      
             'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrE0gSiY9U53V0JRQlmcM4-Q2-vXZL6M8hoQ&s   ',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwCiLh17MJaRxddacGHQdqPHel3svONlDELQ&s ',
        ],
        date: '2025-09-04T09:00:00.000Z',
        startAt: '2025-09-04T09:00:00.000Z',
        endAt: '2025-09-14T23:00:00.000Z',
        venue: { name: 'TIFF Bell Lightbox', address: '350 King St W', city: 'Toronto', state: 'ON', country: 'Canada' },
        price: '$25 – $150',
        priceInfo: '$25 – $150 per screening',
        location: { lat: 43.6452, lng: -79.3907, address: '350 King St W, Toronto, ON' },
    },
    {
        _id: 'ev2',
        name: 'Montreal Jazz Festival',
        title: 'Montreal Jazz Festival',
        category: 'Music',
        description: 'The Montreal International Jazz Festival is the largest jazz festival in the world, recognized by the Guinness World Records. Held annually in late June and early July, it features over 500 concerts, with hundreds of free outdoor performances in the heart of downtown Montreal.',
        imageUrl:             'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_Rwvvov0SjzIggoEQECsJ7xh2AbA2x7St6w&s',

        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0xjT2tUuZvHJzNfNW4C7AgKcyrXX1TWuvMw&s',
            ' https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSUFMj5CKSZhD5ysgvOod-sqgwdsdX438GSxA&s ',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_Rwvvov0SjzIggoEQECsJ7xh2AbA2x7St6w&s'
        ],
        date: '2025-06-26T17:00:00.000Z',
        startAt: '2025-06-26T17:00:00.000Z',
        endAt: '2025-07-05T23:59:00.000Z',
        venue: { name: 'Quartier des Spectacles', address: 'Place des Arts', city: 'Montreal', state: 'QC', country: 'Canada' },
        price: 'Free – $120',
        priceInfo: 'Outdoor concerts free, indoor ticketed from $30',
        location: { lat: 45.5088, lng: -73.5630, address: 'Place des Arts, Montreal, QC' },
    },
    {
        _id: 'ev3',
        name: 'Calgary Stampede',
        title: 'Calgary Stampede',
        category: 'Cultural Festival',
        description: 'Known as The Greatest Outdoor Show on Earth, the Calgary Stampede is a world-famous rodeo, exhibition, and festival held every July. It features chuck wagon races, rodeo competitions, midway rides, live music, Indigenous cultural displays, and the famous Stampede Breakfast — all free pancake breakfasts held across the city.',
        imageUrl:        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMAbZahLcvlT-1tsYkuc96A3IsbXl-O0xHCA&s' ,
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMAbZahLcvlT-1tsYkuc96A3IsbXl-O0xHCA&s',
       'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMAbZahLcvlT-1tsYkuc96A3IsbXl-O0xHCA&s' ,
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDPJnw9E_lX79Q4dh1JecQ-6IZgtp-jGZRIQ&s',
        ],
        date: '2025-07-04T08:00:00.000Z',
        startAt: '2025-07-04T08:00:00.000Z',
        endAt: '2025-07-13T23:00:00.000Z',
        venue: { name: 'Stampede Park', address: '1410 Olympic Way SE', city: 'Calgary', state: 'AB', country: 'Canada' },
        price: '$20 – $80',
        priceInfo: 'General admission from $20, rodeo tickets from $45',
        location: { lat: 51.0375, lng: -114.0509, address: '1410 Olympic Way SE, Calgary, AB' },
    },
    {
        _id: 'ev4',
        name: 'Canada Day Celebrations Ottawa',
        title: 'Canada Day Celebrations Ottawa',
        category: 'National Holiday',
        description: 'Canada\'s capital hosts the biggest Canada Day celebration in the country. Parliament Hill comes alive with live concerts, cultural performances, citizenship ceremonies, and the spectacular evening fireworks show over the Ottawa River. Free and open to all, it draws hundreds of thousands of visitors every July 1st.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_0TZBSSV-XldDfpL281rTFD6JwUMlBArsqg&s  ',
        images: [
            '',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_0TZBSSV-XldDfpL281rTFD6JwUMlBArsqg&s  ',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMAbZahLcvlT-1tsYkuc96A3IsbXl-O0xHCA&s' ,
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDPJnw9E_lX79Q4dh1JecQ-6IZgtp-jGZRIQ&s',
        ],
        date: '2025-07-01T10:00:00.000Z',
        startAt: '2025-07-01T10:00:00.000Z',
        endAt: '2025-07-01T23:30:00.000Z',
        venue: { name: 'Parliament Hill', address: 'Wellington St', city: 'Ottawa', state: 'ON', country: 'Canada' },
        price: 'Free',
        priceInfo: 'Free admission — open to all',
        location: { lat: 45.4236, lng: -75.7009, address: 'Wellington St, Ottawa, ON' },
    },
  
    {
        _id: 'ev7',
        name: 'Winterlude Ottawa',
        title: 'Winterlude Ottawa',
        category: 'Winter Festival',
        description: 'Winterlude is Canada\'s national winter festival, held in Ottawa and Gatineau every February. Highlights include skating on the UNESCO World Heritage Rideau Canal — the world\'s largest naturally frozen skating rink — plus elaborate ice sculptures, snow slides, live performances, and family activities across multiple sites.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDPJnw9E_lX79Q4dh1JecQ-6IZgtp-jGZRIQ&s',
        images: [
           'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDPJnw9E_lX79Q4dh1JecQ-6IZgtp-jGZRIQ&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDPJnw9E_lX79Q4dh1JecQ-6IZgtp-jGZRIQ&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDPJnw9E_lX79Q4dh1JecQ-6IZgtp-jGZRIQ&s',
        ],
        date: '2026-01-30T09:00:00.000Z',
        startAt: '2026-01-30T09:00:00.000Z',
        endAt: '2026-02-16T21:00:00.000Z',
        venue: { name: 'Rideau Canal & Confederation Park', address: 'Queen Elizabeth Driveway', city: 'Ottawa', state: 'ON', country: 'Canada' },
        price: 'Free',
        priceInfo: 'Free — skate rentals available on site',
        location: { lat: 45.4112, lng: -75.6898, address: 'Queen Elizabeth Driveway, Ottawa, ON' },
    },
   
    {
        _id: 'ev11',
        name: 'Quebec Winter Carnival',
        title: 'Quebec Winter Carnival',
        category: 'Winter Festival',
        description: 'The Quebec City Winter Carnival is the world\'s largest winter carnival, held every February. Bonhomme Carnaval, the iconic snowman mascot, hosts events including the famous Ice Palace, night parades, canoe races across the St. Lawrence River, snow sculptures, ice slides, and the popular Carnival outdoor bars with traditional caribou cocktail.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFWlc7bPP06d2F8ZGDdIwSd2o8AQIeOz8qMw&s',
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTV48NpIAXpOhEavtdpv5T-5jOij-NjJmLEYk1vPhYOvg&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSuNBn6XS0oycJaWbdnoyoY708v89nulNI2qk2sjYP-ZA&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMT1GCN0uYJJbs62NlAr2nQdbtV_V15y2Aaw&s',
        ],
        date: '2026-01-29T10:00:00.000Z',
        startAt: '2026-01-29T10:00:00.000Z',
        endAt: '2026-02-15T22:00:00.000Z',
        venue: { name: 'Old Quebec City', address: 'Plains of Abraham & Old Port', city: 'Quebec City', state: 'QC', country: 'Canada' },
        price: '$22 – $28',
        priceInfo: 'Effigy (pass) $22 adults, children under 12 free',
        location: { lat: 46.8139, lng: -71.2082, address: 'Plains of Abraham, Quebec City, QC' },
    },
    {
        _id: 'ev12',
        name: 'Vancouver Cherry Blossom Festival',
        title: 'Vancouver Cherry Blossom Festival',
        category: 'Nature & Cultural',
        description: 'The Vancouver Cherry Blossom Festival celebrates the blooming of over 40,000 cherry trees across the city every spring. Events include the Haiku Invitational, Big Picnic under the blossoms, tree tours, art installations, and cultural performances. Stanley Park and Queen Elizabeth Park offer spectacular blossom viewing.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRoHNIO_289Kn8v4VYK-rfHjQ3z8-d5MN21yw&s',
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLc0gSy2XggTOEOM9UJTlDUT4SLLo3SrBlvTcRUuzPlw&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHpf1Y2atmwnOvzBPvA0-eNKpQUHnGyuPj3Q&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwvFvEAks3g2gfNeelRIFsyar7rl0WlnypYw&s',
        ],
        date: '2026-03-21T09:00:00.000Z',
        startAt: '2026-03-21T09:00:00.000Z',
        endAt: '2026-04-20T20:00:00.000Z',
        venue: { name: 'Stanley Park & City-wide', address: 'Stanley Park', city: 'Vancouver', state: 'BC', country: 'Canada' },
        price: 'Free – $35',
        priceInfo: 'Most events free, Big Picnic tickets from $35',
        location: { lat: 49.3043, lng: -123.1443, address: 'Stanley Park, Vancouver, BC' },
    },
    {
        _id: 'ev13',
        name: 'Toronto Pride Festival',
        title: 'Toronto Pride Festival',
        category: 'Cultural Festival',
        description: 'Toronto Pride is one of the largest Pride festivals in the world, drawing over one million participants every June. The 10-day celebration includes the legendary Pride Parade on Yonge Street, Trans March, Dyke March, film festival, concerts, community events, and the iconic street fair on Church Street. It is a powerful celebration of love, diversity, and inclusion.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQiqaXeVa7pzq60fU4ex-AE3gpU85D2uUeDqQ&s',
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSrcmqsodyXaSbop8zA59lNgBVD4kiI9OTfNGIwPha0VQ&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSuNBn6XS0oycJaWbdnoyoY708v89nulNI2qk2sjYP-ZA&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMT1GCN0uYJJbs62NlAr2nQdbtV_V15y2Aaw&s',
        ],
        date: '2025-06-20T10:00:00.000Z',
        startAt: '2025-06-20T10:00:00.000Z',
        endAt: '2025-06-29T23:00:00.000Z',
        venue: { name: 'Church-Wellesley Village', address: 'Church St & Wellesley St', city: 'Toronto', state: 'ON', country: 'Canada' },
        price: 'Free',
        priceInfo: 'Free — ticketed concerts available separately',
        location: { lat: 43.6654, lng: -79.3818, address: 'Church St, Toronto, ON' },
    },
    {
        _id: 'ev14',
        name: 'Edmonton Folk Music Festival',
        title: 'Edmonton Folk Music Festival',
        category: 'Music',
        description: 'The Edmonton Folk Music Festival is one of Canada\'s best-loved outdoor music festivals, held every August in the beautiful Gallagher Park overlooking the North Saskatchewan River valley. The four-day festival features artists from folk, roots, blues, bluegrass, country, and world music traditions on multiple stages.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaBIqQbXWuzxGfZCv2K1XPVjikWIneJly-aQ&s',
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSuNBn6XS0oycJaWbdnoyoY708v89nulNI2qk2sjYP-ZA&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMT1GCN0uYJJbs62NlAr2nQdbtV_V15y2Aaw&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwvFvEAks3g2gfNeelRIFsyar7rl0WlnypYw&s',
        ],
        date: '2025-08-07T12:00:00.000Z',
        startAt: '2025-08-07T12:00:00.000Z',
        endAt: '2025-08-10T22:30:00.000Z',
        venue: { name: 'Gallagher Park', address: '9310 98 Ave NW', city: 'Edmonton', state: 'AB', country: 'Canada' },
        price: '$50 – $240',
        priceInfo: 'Single day from $50, full weekend passes from $195',
        location: { lat: 53.5283, lng: -113.4735, address: '9310 98 Ave NW, Edmonton, AB' },
    },
    {
        _id: 'ev15',
        name: 'Nuit Blanche Toronto',
        title: 'Nuit Blanche Toronto',
        category: 'Arts & Culture',
        description: 'Nuit Blanche is a free all-night contemporary art event transforming Toronto\'s streets, parks, and public spaces from dusk to dawn every fall. Hundreds of art installations, performances, and exhibitions take over the city, with participation from local and international artists. It is one of the most attended free art events in North America.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRwSlfVPT01EH3Ik-fRXG9FXpmRkTVexrdjg&s',
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSuNBn6XS0oycJaWbdnoyoY708v89nulNI2qk2sjYP-ZA&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMT1GCN0uYJJbs62NlAr2nQdbtV_V15y2Aaw&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwvFvEAks3g2gfNeelRIFsyar7rl0WlnypYw&s',
        ],
        date: '2025-10-04T19:00:00.000Z',
        startAt: '2025-10-04T19:00:00.000Z',
        endAt: '2025-10-05T07:00:00.000Z',
        venue: { name: 'Downtown Toronto (City-wide)', address: 'Nathan Phillips Square & Surroundings', city: 'Toronto', state: 'ON', country: 'Canada' },
        price: 'Free',
        priceInfo: 'Completely free — no tickets required',
        location: { lat: 43.6529, lng: -79.3849, address: 'Nathan Phillips Square, Toronto, ON' },
    },
    {
        _id: 'ev16',
        name: 'Banff Mountain Film and Book Festival',
        title: 'Banff Mountain Film and Book Festival',
        category: 'Film & Adventure',
        description: 'The Banff Centre Mountain Film and Book Festival is the world\'s premier mountain culture event, held every November in the stunning Rocky Mountain town of Banff. It showcases the best mountain, adventure, and exploration films from around the world, alongside award-winning mountain literature and speakers.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXR_hRAfUVwAHvTAQmqZ6chPFIhnLsFIIOhA&s',
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHpf1Y2atmwnOvzBPvA0-eNKpQUHnGyuPj3Q&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSuNBn6XS0oycJaWbdnoyoY708v89nulNI2qk2sjYP-ZA&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMT1GCN0uYJJbs62NlAr2nQdbtV_V15y2Aaw&s',
        ],
        date: '2025-10-25T09:00:00.000Z',
        startAt: '2025-10-25T09:00:00.000Z',
        endAt: '2025-11-02T22:00:00.000Z',
        venue: { name: 'Banff Centre for Arts and Creativity', address: '107 Tunnel Mountain Dr', city: 'Banff', state: 'AB', country: 'Canada' },
        price: '$20 – $60',
        priceInfo: 'Single screenings from $20, passes from $150',
        location: { lat: 51.1794, lng: -115.5708, address: '107 Tunnel Mountain Dr, Banff, AB' },
    },
    {
        _id: 'ev17',
        name: 'Halifax Seafood Festival',
        title: 'Halifax Seafood Festival',
        category: 'Food & Drink',
        description: 'The Halifax Lobster Crawl and Seafood Festival celebrates Nova Scotia\'s incredible seafood culture every February. Restaurants, fishermen, and food lovers come together for lobster dinners, seafood tastings, cooking demonstrations, and harbour tours. It is the perfect celebration of Atlantic Canada\'s most prized culinary treasures.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTl3jp9WSIuPEVoZY2Zk0DPgnSw4dYmvKpc-w&s',
        images: [
            'https://images.unsplash.com/photo-1559847844-5315695dadae?w=800',
            'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800',
            'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800',
        ],
        date: '2026-02-06T11:00:00.000Z',
        startAt: '2026-02-06T11:00:00.000Z',
        endAt: '2026-02-16T21:00:00.000Z',
        venue: { name: 'Halifax Waterfront', address: 'Lower Water St', city: 'Halifax', state: 'NS', country: 'Canada' },
        price: '$35 – $120',
        priceInfo: 'Lobster dinner events from $35 per person',
        location: { lat: 44.6476, lng: -63.5728, address: 'Lower Water St, Halifax, NS' },
    },
    {
        _id: 'ev18',
        name: 'Ottawa Bluesfest',
        title: 'Ottawa Bluesfest',
        category: 'Music',
        description: 'Ottawa Bluesfest is one of the largest music festivals in Canada and the largest blues festival in North America. Held every July at LeBreton Flats Park near the Ottawa River, it features over 100 artists across multiple stages over 10 days, spanning blues, rock, pop, folk, hip-hop, and world music.',
        imageUrl: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=800',
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQvbY_xWaxgxJu3Cb1RuQpGtDzMitxpkctstQ&s',
            'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800',
            'https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=800',
        ],
        date: '2025-07-04T16:00:00.000Z',
        startAt: '2025-07-04T16:00:00.000Z',
        endAt: '2025-07-13T23:30:00.000Z',
        venue: { name: 'LeBreton Flats Park', address: 'Fleet St', city: 'Ottawa', state: 'ON', country: 'Canada' },
        price: '$30 – $180',
        priceInfo: 'Single day from $30, full festival pass from $150',
        location: { lat: 45.4201, lng: -75.7197, address: 'Fleet St, Ottawa, ON' },
    },
    {
        _id: 'ev19',
        name: 'Taste of the Danforth Toronto',
        title: 'Taste of the Danforth Toronto',
        category: 'Food & Drink',
        description: 'Taste of the Danforth is North America\'s largest Greek street festival, held every August along Danforth Avenue in Toronto\'s Greektown. Over 1.6 million people attend to enjoy authentic Greek food, live music on multiple stages, dancing, and cultural activities. The three-day event transforms the street into a massive outdoor celebration.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjTQGNg14bQBdxh8ydBtTzr3IDDQmpTAox0g&s',
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQv4asVgruM8wmW0oyWefUb7sHiGk44IgHNtg&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMT1GCN0uYJJbs62NlAr2nQdbtV_V15y2Aaw&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwvFvEAks3g2gfNeelRIFsyar7rl0WlnypYw&s',
        ],
        date: '2025-08-08T11:00:00.000Z',
        startAt: '2025-08-08T11:00:00.000Z',
        endAt: '2025-08-10T23:00:00.000Z',
        venue: { name: 'Danforth Avenue (Greektown)', address: 'Danforth Ave between Broadview and Jones', city: 'Toronto', state: 'ON', country: 'Canada' },
        price: 'Free',
        priceInfo: 'Free entry — food and drink purchased separately',
        location: { lat: 43.6789, lng: -79.3517, address: 'Danforth Ave, Toronto, ON' },
    },
    {
        _id: 'ev20',
        name: 'Whistler Film Festival',
        title: 'Whistler Film Festival',
        category: 'Film & Arts',
        description: 'The Whistler Film Festival is Canada\'s premier destination film festival, held every December in the mountain resort town of Whistler, BC. It showcases Canadian and international films through screenings, industry panels, and the prestigious Whistler Film Awards, all set against the backdrop of the stunning Whistler Blackcomb mountains.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7jjop_P0ggCoiEQU8cDY_d0agNIk80ps7Cw&s',
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwvFvEAks3g2gfNeelRIFsyar7rl0WlnypYw&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMT1GCN0uYJJbs62NlAr2nQdbtV_V15y2Aaw&s',
            'https://images.unsplash.com/photo-1524985069026-dd778a71c7b4?w=800',
        ],
        date: '2025-12-03T10:00:00.000Z',
        startAt: '2025-12-03T10:00:00.000Z',
        endAt: '2025-12-07T22:00:00.000Z',
        venue: { name: 'Whistler Conference Centre', address: '4010 Whistler Way', city: 'Whistler', state: 'BC', country: 'Canada' },
        price: '$15 – $45',
        priceInfo: 'Single screenings from $15, passes from $99',
        location: { lat: 50.1163, lng: -122.9574, address: '4010 Whistler Way, Whistler, BC' },
    },
    {

        _id: 'ev21',
        name: 'Vancouver International Film Festival',
        title: 'Vancouver International Film Festival',
        category: 'Film & Arts',
        description: 'VIFF is one of the largest film festivals in North America, screening over 300 films from more than 70 countries every fall in Vancouver. Known for its exceptional focus on Canadian and East Asian cinema, the festival runs for two weeks with screenings, filmmaker Q&As, and industry events across multiple downtown venues.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtL3o1xj7KlVrMya_hToO9Fc-UnpA52e0Kdg&s',
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBfyERV-LMLXDmoRqqEiBXU649laq0im_Xkw&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8VcCCTrZtNB7V8tOqk5WqNl_srvcwetlrEQ&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6u-SzcWZ2DnA6fMcTw9ZMfCwlQrttS1afoA&s',
        ],
        date: '2025-09-25T10:00:00.000Z',
        startAt: '2025-09-25T10:00:00.000Z',
        endAt: '2025-10-10T23:00:00.000Z',
        venue: { name: 'Vancouver Playhouse & Cinematheque', address: '600 Hamilton St', city: 'Vancouver', state: 'BC', country: 'Canada' },
        price: '$15 – $40',
        priceInfo: 'Single screenings from $15, festival passes from $99',
        location: { lat: 49.2827, lng: -123.1207, address: '600 Hamilton St, Vancouver, BC' },
    },
    {
        _id: 'ev22',
        name: 'Osheaga Music and Arts Festival',
        title: 'Osheaga Music and Arts Festival',
        category: 'Music',
        description: 'Osheaga is Montreal\'s biggest music festival, held every August on Île Sainte-Hélène in the St. Lawrence River. The three-day event draws over 150,000 attendees with headliners spanning indie rock, pop, electronic, and hip-hop across six stages. It is consistently ranked among the top music festivals in North America.',
        imageUrl: 'https://www.google.com/imgres?q=canada%20events%20image&imgurl=https%3A%2F%2Fwww.freep.com%2Fgcdn%2F-mm-%2F238ddbdc565daa96bb6fedb2616a3dabbd496a7c%2Fc%3D0-301-4300-2730%2Flocal%2F-%2Fmedia%2F2018%2F07%2F02%2FDetroitFreeP%2FDetroitFreePress%2F636661199726037106-AP-Canada-Day-JDT119.jpg%3Fwidth%3D700%26height%3D396%26fit%3Dcrop%26format%3Dpjpg%26auto%3Dwebp&imgrefurl=https%3A%2F%2Fwww.freep.com%2Fpicture-gallery%2Fnews%2Fnation%2F2018%2F07%2F02%2Fcanada-day-2018%2F36553041%2F&docid=EJVu4yukQVAVgM&tbnid=T-ww4qqrYvy2WM&vet=12ahUKEwiett6rwPuUAxWkzTgGHQxlEQc4ChCc8A56BAhaEAE..i&w=700&h=396&hcb=2&ved=2ahUKEwiett6rwPuUAxWkzTgGHQxlEQc4ChCc8A56BAhaEAE',
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzNqK6ERcUrioY5RM90mBxCGhhuwPCyEV9tg&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8VcCCTrZtNB7V8tOqk5WqNl_srvcwetlrEQ&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6u-SzcWZ2DnA6fMcTw9ZMfCwlQrttS1afoA&s',
        ],
        date: '2025-08-01T12:00:00.000Z',
        startAt: '2025-08-01T12:00:00.000Z',
        endAt: '2025-08-03T23:59:00.000Z',
        venue: { name: 'Parc Jean-Drapeau', address: '1 Circuit Gilles Villeneuve', city: 'Montreal', state: 'QC', country: 'Canada' },
        price: '$120 – $360',
        priceInfo: 'Single day from $120, 3-day pass from $310',
        location: { lat: 45.5131, lng: -73.5324, address: 'Parc Jean-Drapeau, Montreal, QC' },
    },
    {
        _id: 'ev23',
        name: 'Canadian National Exhibition (CNE)',
        title: 'Canadian National Exhibition (CNE)',
        category: 'Fair & Exhibition',
        description: 'The Canadian National Exhibition, known as "The Ex," is one of the largest annual fairs in North America. Held at Exhibition Place in Toronto every August, it runs for 18 days and features midway rides, international food vendors, live concerts, air shows, agricultural showcases, and consumer exhibitions. It has been running since 1879.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSea_dEtUQ9W0HGDZN7rtAklxeyDUY8M3TEgw&s',
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTSTBPXRurGFXvzbCSTVfR17RhBVh6M3VTtPA&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMrPLEr_p50ruhdKNYrUBg3M31YDCDAaAXGQ&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxEZXORPx1Cf_alVoe_5v4Eo5yRgWI_8uqOw&s',
        ],
        date: '2025-08-15T10:00:00.000Z',
        startAt: '2025-08-15T10:00:00.000Z',
        endAt: '2025-09-01T22:00:00.000Z',
        venue: { name: 'Exhibition Place', address: '100 Princes Blvd', city: 'Toronto', state: 'ON', country: 'Canada' },
        price: '$20 – $35',
        priceInfo: 'General admission from $20, children under 2 free',
        location: { lat: 43.6338, lng: -79.4195, address: '100 Princes Blvd, Toronto, ON' },
    },
    {
        _id: 'ev24',
        name: 'Winnipeg Folk Festival',
        title: 'Winnipeg Folk Festival',
        category: 'Music',
        description: 'One of the longest-running folk festivals in the world, the Winnipeg Folk Festival has been held every July since 1974 at Birds Hill Provincial Park. The four-day outdoor event features over 70 artists from folk, roots, world music, and beyond across seven stages, set in a stunning natural park setting north of Winnipeg.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaBIqQbXWuzxGfZCv2K1XPVjikWIneJly-aQ&s',
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaBIqQbXWuzxGfZCv2K1XPVjikWIneJly-aQ&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSuNBn6XS0oycJaWbdnoyoY708v89nulNI2qk2sjYP-ZA&s',
            'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=800',
        ],
        date: '2025-07-10T12:00:00.000Z',
        startAt: '2025-07-10T12:00:00.000Z',
        endAt: '2025-07-13T22:30:00.000Z',
        venue: { name: 'Birds Hill Provincial Park', address: 'Birds Hill Provincial Park', city: 'Winnipeg', state: 'MB', country: 'Canada' },
        price: '$60 – $270',
        priceInfo: 'Single day from $60, full weekend pass from $235',
        location: { lat: 50.0391, lng: -96.8716, address: 'Birds Hill Provincial Park, MB' },
    },
    {
        _id: 'ev25',
        name: 'Just For Laughs Comedy Festival',
        title: 'Just For Laughs Comedy Festival',
        category: 'Comedy',
        description: 'Just For Laughs is the world\'s largest international comedy festival, held every July in Montreal. Since 1983, it has brought together comedians from around the world for galas, club shows, free outdoor performances, and industry events. Past performers include Jerry Seinfeld, Dave Chappelle, and John Mulaney. The festival attracts over 2 million attendees annually.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQg0F3UOM7SdLYPW10yjMjgC6sr1muI139_Iw&s',
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgDmsu4L9_vyhT7-jRMZZkSyHj_EzJCSgmIQ&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-yir5PVEyBL29fWkRvLnvRFlj3vqHhZuNcg&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0xjT2tUuZvHJzNfNW4C7AgKcyrXX1TWuvMw&s',
        ],
        date: '2025-07-16T18:00:00.000Z',
        startAt: '2025-07-16T18:00:00.000Z',
        endAt: '2025-07-27T23:59:00.000Z',
        venue: { name: 'Quartier des Spectacles & Old Montreal', address: 'Sainte-Catherine St W', city: 'Montreal', state: 'QC', country: 'Canada' },
        price: 'Free – $95',
        priceInfo: 'Outdoor shows free, ticketed galas from $45',
        location: { lat: 45.5106, lng: -73.5632, address: 'Sainte-Catherine St W, Montreal, QC' },
    },
    {
        _id: 'ev26',
        name: 'Niagara Grape & Wine Festival',
        title: 'Niagara Grape & Wine Festival',
        category: 'Food & Drink',
        description: 'The Niagara Grape and Wine Festival is Canada\'s largest wine festival, celebrating the harvest of the Niagara wine region every September. Held in St. Catharines for over 70 years, the 10-day festival features wine tastings, vineyard tours, the Grand Parade, live music, and culinary events showcasing world-class Niagara wines like ice wine and Riesling.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTl3jp9WSIuPEVoZY2Zk0DPgnSw4dYmvKpc-w&s',
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTl3jp9WSIuPEVoZY2Zk0DPgnSw4dYmvKpc-w&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR2VkvZQbp8cz7nQ9rbvNOvLJstzwnEDookrw&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0xjT2tUuZvHJzNfNW4C7AgKcyrXX1TWuvMw&s',
        ],
        date: '2025-09-19T11:00:00.000Z',
        startAt: '2025-09-19T11:00:00.000Z',
        endAt: '2025-09-28T22:00:00.000Z',
        venue: { name: 'Montebello Park & Downtown St. Catharines', address: '64 Ontario St', city: 'St. Catharines', state: 'ON', country: 'Canada' },
        price: 'Free – $85',
        priceInfo: 'Grand Parade free, tasting events from $30',
        location: { lat: 43.1594, lng: -79.2469, address: '64 Ontario St, St. Catharines, ON' },
    },
    {
        _id: 'ev27',
        name: 'Saskatchewan Jazz Festival',
        title: 'Saskatchewan Jazz Festival',
        category: 'Music',
        description: 'The TD Saskatchewan Jazz Festival is one of Canada\'s premier jazz events, held every June in Saskatoon\'s historic Broadway district and Bessborough Hotel grounds. The 10-day festival features over 500 performances, with a mix of free outdoor concerts and ticketed indoor shows, drawing artists from jazz, blues, soul, and world music.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRYxCByNg13KNyqrsiz-ymugV_thWBPtpjwjg&s',
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQeCtzTdWQmZZNlQO_6I-Lh1uwl4ciniFuhYg&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0qOjZ6VFXPUnjB0dErfwHQRJfNz3xIxJTlw&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQ458YHnp1_nMOzhGn184NBN2cLA7su0LJog&s',
        ],
        date: '2025-06-20T17:00:00.000Z',
        startAt: '2025-06-20T17:00:00.000Z',
        endAt: '2025-06-29T23:00:00.000Z',
        venue: { name: 'Bessborough Hotel & Riverbank', address: '601 Spadina Crescent E', city: 'Saskatoon', state: 'SK', country: 'Canada' },
        price: 'Free – $75',
        priceInfo: 'Outdoor stages free, indoor ticketed from $25',
        location: { lat: 52.1320, lng: -106.6700, address: '601 Spadina Crescent E, Saskatoon, SK' },
    },
    {
        _id: 'ev28',
        name: 'PEI International Shellfish Festival',
        title: 'PEI International Shellfish Festival',
        category: 'Food & Drink',
        description: 'The Prince Edward Island International Shellfish Festival is a beloved celebration of PEI\'s world-famous oysters, mussels, clams, and lobster, held every September in Charlottetown. The four-day waterfront festival features oyster shucking competitions, chef showcases, live music, and the chance to taste some of the finest shellfish in the world.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXjt5FpMM9b-qgtws7SDF9rvwTPeyAv0MbOA&s',
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3t-W4W85e8f3lmJNZc6lAssVYGb2_CPeaxA&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0xjT2tUuZvHJzNfNW4C7AgKcyrXX1TWuvMw&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR2VkvZQbp8cz7nQ9rbvNOvLJstzwnEDookrw&s',
        ],
        date: '2025-09-18T11:00:00.000Z',
        startAt: '2025-09-18T11:00:00.000Z',
        endAt: '2025-09-21T21:00:00.000Z',
        venue: { name: 'Peake\'s Wharf', address: '1 Peakes Wharf', city: 'Charlottetown', state: 'PE', country: 'Canada' },
        price: '$15 – $60',
        priceInfo: 'General admission from $15, tasting passes from $45',
        location: { lat: 46.2382, lng: -63.1311, address: '1 Peakes Wharf, Charlottetown, PE' },
    },
    {
        _id: 'ev29',
        name: 'Luminato Festival Toronto',
        title: 'Luminato Festival Toronto',
        category: 'Arts & Culture',
        description: 'Luminato is Toronto\'s annual festival of arts and creativity, held every June at Harbourfront Centre and venues across the city. The multidisciplinary festival presents world premieres and boundary-pushing work in theatre, dance, music, visual arts, and digital media, with a mix of free and ticketed programming for all audiences.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRiazmBbz90J7D6H4AZHIGl9JIO_eihXA1qFw&s',
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzzkySDkCPHkTRWYDZ3ymlDY2QXxjMc7UkuQ&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRiazmBbz90J7D6H4AZHIGl9JIO_eihXA1qFw&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMT1GCN0uYJJbs62NlAr2nQdbtV_V15y2Aaw&s',
        ],
        date: '2025-06-06T10:00:00.000Z',
        startAt: '2025-06-06T10:00:00.000Z',
        endAt: '2025-06-15T22:00:00.000Z',
        venue: { name: 'Harbourfront Centre', address: '235 Queens Quay W', city: 'Toronto', state: 'ON', country: 'Canada' },
        price: 'Free – $65',
        priceInfo: 'Many events free, ticketed shows from $25',
        location: { lat: 43.6388, lng: -79.3816, address: '235 Queens Quay W, Toronto, ON' },
    },
    {
        _id: 'ev30',
        name: 'Carnaval de Québec (Summer Edition)',
        title: 'Fête Nationale du Québec',
        category: 'Cultural Festival',
        description: 'La Fête Nationale du Québec, celebrated on June 24th, is Quebec\'s national holiday and one of the most vibrant cultural celebrations in Canada. Massive outdoor concerts, bonfires, fireworks, and community gatherings take place across all of Quebec. The main stage on the Plains of Abraham in Quebec City draws tens of thousands for a spectacular free concert.',
        imageUrl: '',
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSBDVxmkQ7HetwuPMHP8Sw13ORSCQDm750stQ&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXCWuQvoBiHEYH57MRFQWeHu6J2vgkgjeUJw&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMT1GCN0uYJJbs62NlAr2nQdbtV_V15y2Aaw&s',
        ],
        date: '2025-06-24T16:00:00.000Z',
        startAt: '2025-06-24T16:00:00.000Z',
        endAt: '2025-06-24T23:59:00.000Z',
        venue: { name: 'Plains of Abraham', address: '835 Wilfrid-Laurier Ave', city: 'Quebec City', state: 'QC', country: 'Canada' },
        price: 'Free',
        priceInfo: 'Completely free — open to all',
        location: { lat: 46.8019, lng: -71.2144, address: '835 Wilfrid-Laurier Ave, Quebec City, QC' },
    },
    {
        _id: 'ev31',
        name: 'Edmonton International Fringe Festival',
        title: 'Edmonton International Fringe Festival',
        category: 'Theatre & Arts',
        description: 'The Edmonton International Fringe Theatre Festival is the oldest and largest fringe festival in North America, held every August in the Old Strathcona neighbourhood. Over 200 theatre companies from around the world perform in 55+ venues for 11 days, covering comedy, drama, improv, puppetry, and performance art. Most tickets are under $20.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXR_hRAfUVwAHvTAQmqZ6chPFIhnLsFIIOhA&s',
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXR_hRAfUVwAHvTAQmqZ6chPFIhnLsFIIOhA&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHpf1Y2atmwnOvzBPvA0-eNKpQUHnGyuPj3Q&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8bkcDjVjbbF2hGQWmsqo5oL4UzsjpOZAneQ&s',
        ],
        date: '2025-08-14T12:00:00.000Z',
        startAt: '2025-08-14T12:00:00.000Z',
        endAt: '2025-08-24T23:00:00.000Z',
        venue: { name: 'Old Strathcona', address: '83 Ave & Whyte Ave', city: 'Edmonton', state: 'AB', country: 'Canada' },
        price: '$5 – $18',
        priceInfo: 'Most shows $10–$18, street performances free',
        location: { lat: 53.5198, lng: -113.5049, address: '83 Ave & Whyte Ave, Edmonton, AB' },
    },
    {
        _id: 'ev32',
        name: 'Celebration of Light Vancouver',
        title: 'Honda Celebration of Light Vancouver',
        category: 'Festival & Fireworks',
        description: 'The Honda Celebration of Light is the world\'s largest offshore fireworks competition, held every summer at English Bay in Vancouver. Three countries compete over three nights with spectacular synchronized fireworks displays set to music, drawing over one million spectators to the waterfront. It is one of the most beloved summer traditions in Vancouver.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnubsvHvMcJAnuXw5hLuQCO9zSwTpmuJlpBQ&s',
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsgJ2PalUuYfAYRJjClKUWmbJfFCtjg_FXWg&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSlqc0GaTT8siBUdXNJnSYrwHQojYS4uhMGWQ&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwvFvEAks3g2gfNeelRIFsyar7rl0WlnypYw&s',
        ],
        date: '2025-07-26T22:00:00.000Z',
        startAt: '2025-07-26T22:00:00.000Z',
        endAt: '2025-08-02T23:30:00.000Z',
        venue: { name: 'English Bay Beach', address: 'English Bay Beach', city: 'Vancouver', state: 'BC', country: 'Canada' },
        price: 'Free',
        priceInfo: 'Free to watch from the beach and surrounding areas',
        location: { lat: 49.2849, lng: -123.1440, address: 'English Bay Beach, Vancouver, BC' },
    },
    {
        _id: 'ev33',
        name: 'Yukon Quest Sled Dog Race',
        title: 'Yukon Quest International Sled Dog Race',
        category: 'Sport & Adventure',
        description: 'The Yukon Quest is one of the toughest sled dog races in the world, covering 1,600 km between Fairbanks, Alaska and Whitehorse, Yukon through some of the most remote and extreme wilderness on Earth. Held every February, the race takes mushers and their dog teams through temperatures as low as -60°C, mountain passes, and frozen rivers.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRy8XA-zp8pd2XCK4kQ8hoEasCds0uPV15oXQ&s',
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8IERwQ4AjUK4IeRs41V448MNre2ceYIOy5Q&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXj8n1s5l3m2u7e5ZtHqj8h6v9kKz1sV4cQ&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwvFvEAks3g2gfNeelRIFsyar7rl0WlnypYw&s',
        ],
        date: '2026-02-07T09:00:00.000Z',
        startAt: '2026-02-07T09:00:00.000Z',
        endAt: '2026-02-20T18:00:00.000Z',
        venue: { name: 'Whitehorse Waterfront', address: 'Yukon River Waterfront', city: 'Whitehorse', state: 'YT', country: 'Canada' },
        price: 'Free',
        priceInfo: 'Free to spectate at start and finish',
        location: { lat: 60.7212, lng: -135.0568, address: 'Yukon River Waterfront, Whitehorse, YT' },
    },
    {
        _id: 'ev34',
        name: 'Cavendish Beach Music Festival',
        title: 'Cavendish Beach Music Festival',
        category: 'Music',
        description: 'The Cavendish Beach Music Festival is Atlantic Canada\'s biggest country music festival, held every July on the beaches of Prince Edward Island. The three-day event draws world-class country artists to a stunning oceanside stage, with camping, beach activities, and the unique experience of watching live music with the Gulf of St. Lawrence as a backdrop.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSOXBngkvkemjmLxBj7y1B4I_gwKB1ODNyR9A&s',
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ1gMQ1IPK90wdFI762Y9sBT7Gp7PhhrEUPDA&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6yPoQucfW9s4ecxoAi3MIZzLbmamPnNNteQ&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSp7lOb08ZKyWb4wUeH5gWR4wrsZnjKPzv7cQ&s',
        ],
        date: '2025-07-04T15:00:00.000Z',
        startAt: '2025-07-04T15:00:00.000Z',
        endAt: '2025-07-06T23:30:00.000Z',
        venue: { name: 'Cavendish Beach', address: 'Gulf Shore Pkwy', city: 'Cavendish', state: 'PE', country: 'Canada' },
        price: '$115 – $290',
        priceInfo: 'Single day from $115, 3-day pass from $260',
        location: { lat: 46.4946, lng: -63.3960, address: 'Gulf Shore Pkwy, Cavendish, PE' },
    },
    {
        _id: 'ev35',
        name: 'TD Ottawa Jazz Festival',
        title: 'TD Ottawa Jazz Festival',
        category: 'Music',
        description: 'The TD Ottawa Jazz Festival is one of Canada\'s premier jazz events, held every June in the heart of the nation\'s capital. The festival spans 10 days with over 100 concerts featuring world-renowned jazz artists across multiple stages at Confederation Park and indoor venues. Many outdoor performances are free, making it accessible to all music lovers.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQn7b_HE3C79GAvJ6elFHH1lF2T4VzLlHzPcg&s',
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR10mTZN-mZmf3y_8I7s5rzbJg7WfD1u9OR-g&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQiPbTL3C5LIBjju5aJur2A0mq0XeNUd_jCRw&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjTQGNg14bQBdxh8ydBtTzr3IDDQmpTAox0g&s',
        ],
        date: '2025-06-19T17:00:00.000Z',
        startAt: '2025-06-19T17:00:00.000Z',
        endAt: '2025-06-28T23:00:00.000Z',
        venue: { name: 'Confederation Park', address: 'Elgin St & Laurier Ave W', city: 'Ottawa', state: 'ON', country: 'Canada' },
        price: 'Free – $80',
        priceInfo: 'Outdoor stage free, indoor ticketed from $30',
        location: { lat: 45.4231, lng: -75.6917, address: 'Elgin St & Laurier Ave W, Ottawa, ON' },
    },
    {
        _id: 'ev36',
        name: 'Bard on the Beach Shakespeare Festival',
        title: 'Bard on the Beach Shakespeare Festival',
        category: 'Theatre & Arts',
        description: 'Bard on the Beach is Western Canada\'s largest professional Shakespeare festival, held every summer in spectacular tent pavilions at Vanier Park on the shores of English Bay in Vancouver. Running from June to September, the festival presents four productions each season with the stunning backdrop of the mountains and Burrard Inlet.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRDUfA-5602XlUxy-iSUuxWESucy-j-YSnJYg&s',
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmzhGLARvqKCP4617mxpZhA7Kykd5R6vRv9Q&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKsAoSUIr3ZJDEMgW9j8lbKqbMVJvWQF7mLw&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHpf1Y2atmwnOvzBPvA0-eNKpQUHnGyuPj3Q&s',
        ],
        date: '2025-06-05T19:30:00.000Z',
        startAt: '2025-06-05T19:30:00.000Z',
        endAt: '2025-09-20T22:00:00.000Z',
        venue: { name: 'Vanier Park', address: '1695 Whyte Ave', city: 'Vancouver', state: 'BC', country: 'Canada' },
        price: '$30 – $85',
        priceInfo: 'Tickets from $30, preview performances discounted',
        location: { lat: 49.2756, lng: -123.1450, address: '1695 Whyte Ave, Vancouver, BC' },
    },
    {
        _id: 'ev37',
        name: 'Kitchener-Waterloo Oktoberfest',
        title: 'Kitchener-Waterloo Oktoberfest',
        category: 'Cultural Festival',
        description: 'Kitchener-Waterloo Oktoberfest is the largest Bavarian festival outside of Germany and Europe, held every October in the twin cities of Kitchener and Waterloo, Ontario. The 9-day celebration features traditional German beer halls (Festhalles), authentic food, oompah bands, polka dancing, the famous Thanksgiving Day Parade, and cultural events celebrating the region\'s German heritage.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT3KioAq91YbLL8iQAX9dCwOZihlzI9pqrzKQ&s',
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRAc39c__g9BfBbNnpR3BrT7YxOvYUxTNumZQ&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTscPYNi8vRE9FP-eh1AxDfKnljUlZrmOV9IA&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjTQGNg14bQBdxh8ydBtTzr3IDDQmpTAox0g&s',
        ],
        date: '2025-10-10T11:00:00.000Z',
        startAt: '2025-10-10T11:00:00.000Z',
        endAt: '2025-10-18T23:00:00.000Z',
        venue: { name: 'Bingeman\'s & Multiple Festhalles', address: '1380 Victoria St N', city: 'Kitchener', state: 'ON', country: 'Canada' },
        price: '$15 – $55',
        priceInfo: 'Festhalle entry from $15, weekend passes available',
        location: { lat: 43.4516, lng: -80.4925, address: '1380 Victoria St N, Kitchener, ON' },
    },
    {
        _id: 'ev38',
        name: 'Nova Scotia Tattoo',
        title: 'Royal Nova Scotia International Tattoo',
        category: 'Cultural Festival',
        description: 'The Royal Nova Scotia International Tattoo is the world\'s largest annual indoor show, held every July at the Scotiabank Centre in Halifax. This spectacular military-themed event features massed pipes and drums, military bands, precision drill teams, gymnasts, and entertainers from around the world. It is recognized by the Guinness World Records as the largest annual indoor show.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRntQdulg-hYLazDpdLOuz-6MVc2arw6OYUnA&s',
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSj27LV8VtHfGZ5a8ABa28Ia4ikFw0LhzGRTA&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRntQdulg-hYLazDpdLOuz-6MVc2arw6OYUnA&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRntQdulg-hYLazDpdLOuz-6MVc2arw6OYUnA&s',
        ],
        date: '2025-07-01T19:30:00.000Z',
        startAt: '2025-07-01T19:30:00.000Z',
        endAt: '2025-07-05T21:30:00.000Z',
        venue: { name: 'Scotiabank Centre', address: '1800 Argyle St', city: 'Halifax', state: 'NS', country: 'Canada' },
        price: '$35 – $75',
        priceInfo: 'Adult tickets from $35, family packages available',
        location: { lat: 44.6476, lng: -63.5748, address: '1800 Argyle St, Halifax, NS' },
    },
    {
        _id: 'ev39',
        name: 'Mosaïcultures Internationales Montreal',
        title: 'Mosaïcultures Internationales de Montréal',
        category: 'Nature & Cultural',
        description: 'Mosaïcultures Internationales is a world-class horticultural art event held at the Montreal Botanical Garden, showcasing stunning living sculptures crafted from thousands of plants. Countries from around the world compete to create the most elaborate and beautiful plant-based art installations in one of the most impressive botanical gardens in the world.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRAo5kjz2WbMRDL8smGC5ntZ7MucXbtQhqJOQ&s',
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5V6CGY1vZ8gFbZytQ6xiHSL1bAsHx8PP1Tg&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSSm9tV0al7kgxShdGI_fDjkUXYx3E4p2I_A&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwvFvEAks3g2gfNeelRIFsyar7rl0WlnypYw&s',
        ],
        date: '2025-06-21T09:00:00.000Z',
        startAt: '2025-06-21T09:00:00.000Z',
        endAt: '2025-10-05T18:00:00.000Z',
        venue: { name: 'Montreal Botanical Garden', address: '4101 Sherbrooke St E', city: 'Montreal', state: 'QC', country: 'Canada' },
        price: '$21 – $28',
        priceInfo: 'Adults $21, seniors $19, children under 5 free',
        location: { lat: 45.5588, lng: -73.5560, address: '4101 Sherbrooke St E, Montreal, QC' },
    },
    {
        _id: 'ev40',
        name: 'Toronto Caribbean Carnival',
        title: 'Toronto Caribbean Carnival (Caribana)',
        category: 'Cultural Festival',
        description: 'Toronto Caribbean Carnival, widely known as Caribana, is the largest street festival in North America, drawing over one million people every summer. The three-week celebration of Caribbean culture culminates in the Grand Parade along Lake Shore Boulevard — a spectacular showcase of elaborate costumes, steel pan music, soca, calypso, and Caribbean cuisine. It has been a Toronto tradition since 1967.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXCWuQvoBiHEYH57MRFQWeHu6J2vgkgjeUJw&s',
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTWok7OmT1H6xA5AzxJSsRXPh5gRKV-1b9jUw&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRntQdulg-hYLazDpdLOuz-6MVc2arw6OYUnA&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSj27LV8VtHfGZ5a8ABa28Ia4ikFw0LhzGRTA&s',
        ],
        date: '2025-07-18T10:00:00.000Z',
        startAt: '2025-07-18T10:00:00.000Z',
        endAt: '2025-08-04T23:00:00.000Z',
        venue: { name: 'Lake Shore Blvd W & Exhibition Place', address: 'Lake Shore Blvd W', city: 'Toronto', state: 'ON', country: 'Canada' },
        price: 'Free – $45',
        priceInfo: 'Grand Parade viewing free, grandstand from $35',
        location: { lat: 43.6290, lng: -79.4130, address: 'Lake Shore Blvd W, Toronto, ON' },
    },
    {
        _id: 'ev41',
        name: 'Toronto International BuskerFest',
        title: 'Toronto International BuskerFest',
        category: 'Arts & Culture',
        description: 'Toronto International BuskerFest is one of the largest street performer festivals in North America, held every August along the Distillery District and waterfront. Over 100 performers from around the world showcase juggling, acrobatics, comedy, magic, and music. The festival is free to attend and raises funds for Epilepsy Toronto.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlP8Ry-MontzZY7abNiFkd-8S6jlfWFYgB7w&s',
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlP8Ry-MontzZY7abNiFkd-8S6jlfWFYgB7w&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQv4asVgruM8wmW0oyWefUb7sHiGk44IgHNtg&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMT1GCN0uYJJbs62NlAr2nQdbtV_V15y2Aaw&s',
        ],
        date: '2025-08-21T12:00:00.000Z',
        startAt: '2025-08-21T12:00:00.000Z',
        endAt: '2025-08-24T22:00:00.000Z',
        venue: { name: 'Distillery District', address: '55 Mill St', city: 'Toronto', state: 'ON', country: 'Canada' },
        price: 'Free',
        priceInfo: 'Free to attend — donations welcome',
        location: { lat: 43.6503, lng: -79.3596, address: '55 Mill St, Toronto, ON' },
    },
    {
        _id: 'ev42',
        name: 'Vancouver International Jazz Festival',
        title: 'TD Vancouver International Jazz Festival',
        category: 'Music',
        description: 'The TD Vancouver International Jazz Festival is one of the largest jazz festivals in the world, held every June across 40+ venues in Vancouver. The 10-day festival presents over 300 artists and 1,500 musicians from around the globe, with hundreds of free outdoor performances at David Lam Park and throughout the city.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSlaeS8L1Ria_oOPUGsNQC0eVdSrooU0XcJJA&s',
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3ve0pe8N0dLTPV5QybB3CRIwo37fS-Uimrw&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTSaKP2XZN414QdYK0kf_z9mGK1xQguTXrGYg&s',
            'https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=800',
        ],
        date: '2025-06-20T17:00:00.000Z',
        startAt: '2025-06-20T17:00:00.000Z',
        endAt: '2025-06-29T23:00:00.000Z',
        venue: { name: 'David Lam Park & City-wide', address: '1300 Pacific Blvd', city: 'Vancouver', state: 'BC', country: 'Canada' },
        price: 'Free – $80',
        priceInfo: 'Outdoor stages free, ticketed shows from $30',
        location: { lat: 49.2734, lng: -123.1256, address: '1300 Pacific Blvd, Vancouver, BC' },
    },
    {
        _id: 'ev43',
        name: 'Stratford Festival',
        title: 'Stratford Festival',
        category: 'Theatre & Arts',
        description: 'The Stratford Festival in Stratford, Ontario is the largest classical repertory theatre festival in North America. Running from April to November, it presents Shakespeare alongside classic and contemporary works across four stages. The festival has been running since 1953 and attracts over 500,000 visitors annually to the charming town on the Avon River.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTSaKP2XZN414QdYK0kf_z9mGK1xQguTXrGYg&s&s',
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7jjop_P0ggCoiEQU8cDY_d0agNIk80ps7Cw&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKsAoSUIr3ZJDEMgW9j8lbKqbMVJvWQF7mLw&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHpf1Y2atmwnOvzBPvA0-eNKpQUHnGyuPj3Q&s',
        ],
        date: '2025-04-22T19:30:00.000Z',
        startAt: '2025-04-22T19:30:00.000Z',
        endAt: '2025-11-02T22:00:00.000Z',
        venue: { name: 'Festival Theatre', address: '55 Queen St', city: 'Stratford', state: 'ON', country: 'Canada' },
        price: '$30 – $175',
        priceInfo: 'Preview performances from $30, regular from $65',
        location: { lat: 43.3700, lng: -80.9822, address: '55 Queen St, Stratford, ON' },
    },
    {
        _id: 'ev44',
        name: 'Calgary International Blues Festival',
        title: 'Calgary International Blues Festival',
        category: 'Music',
        description: 'The Calgary International Blues Festival is a beloved annual event held every July in Prince\'s Island Park along the Bow River. The three-day festival features world-class blues, soul, and roots artists on two stages with the stunning backdrop of downtown Calgary. Many performances are free, making it one of the most accessible music festivals in Alberta.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTuAwUKwzAJEaT8qd_jfa0aGs9BV3eSVMvvSw&s',
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJDMM9hOgVsLfqQ31rUr21BfW03riY-OENlw&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0VKfpnqlno_6jDnguhP2L573ooY_9qFAkqw&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQvbY_xWaxgxJu3Cb1RuQpGtDzMitxpkctstQ&s',
        ],
        date: '2025-07-18T14:00:00.000Z',
        startAt: '2025-07-18T14:00:00.000Z',
        endAt: '2025-07-20T22:30:00.000Z',
        venue: { name: "Prince's Island Park", address: "Prince's Island Park", city: 'Calgary', state: 'AB', country: 'Canada' },
        price: 'Free – $55',
        priceInfo: 'Free outdoor stage, ticketed shows from $30',
        location: { lat: 51.0520, lng: -114.0710, address: "Prince's Island Park, Calgary, AB" },
    },
    {
        _id: 'ev45',
        name: 'Ottawa Dragon Boat Festival',
        title: 'Ottawa Dragon Boat Festival',
        category: 'Sport & Cultural',
        description: 'The Ottawa Dragon Boat Festival is one of the largest dragon boat festivals in North America, held every June on Mooney\'s Bay Park along the Rideau River. Over 5,000 paddlers compete across two days while thousands of spectators enjoy live music, cultural performances, Asian food vendors, and family activities along the riverbank.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0VKfpnqlno_6jDnguhP2L573ooY_9qFAkqw&s',
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ56gHa_ZAUfU3E0P-I5t6dWSX98qQ_NRgBsw&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSjsVKyuvWLB1sFh1S2LgsOAGYRchAHaJ7lHA&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwvFvEAks3g2gfNeelRIFsyar7rl0WlnypYw&s',
        ],
        date: '2025-06-21T08:00:00.000Z',
        startAt: '2025-06-21T08:00:00.000Z',
        endAt: '2025-06-22T18:00:00.000Z',
        venue: { name: "Mooney's Bay Park", address: '2960 Riverside Dr', city: 'Ottawa', state: 'ON', country: 'Canada' },
        price: 'Free',
        priceInfo: 'Free for spectators',
        location: { lat: 45.3705, lng: -75.6901, address: '2960 Riverside Dr, Ottawa, ON' },
    },
    {
        _id: 'ev46',
        name: 'Sled Island Music & Arts Festival',
        title: 'Sled Island Music & Arts Festival',
        category: 'Music',
        description: 'Sled Island is Calgary\'s acclaimed independent music and arts festival, held every June across 30+ venues in the city. The five-day festival features over 250 bands, comedians, visual artists, and filmmakers, with an eclectic lineup spanning indie rock, metal, electronic, hip-hop, and experimental music. It is known for its intimate venue atmosphere and adventurous programming.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSjsVKyuvWLB1sFh1S2LgsOAGYRchAHaJ7lHA&s',
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSuignwJslhfJcilRUBQUxSFUOWebU5X-9iiA&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSuignwJslhfJcilRUBQUxSFUOWebU5X-9iiA&s',
            'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800',
        ],
        date: '2025-06-18T18:00:00.000Z',
        startAt: '2025-06-18T18:00:00.000Z',
        endAt: '2025-06-22T02:00:00.000Z',
        venue: { name: 'MacEwan Hall & City-wide Venues', address: '2500 University Dr NW', city: 'Calgary', state: 'AB', country: 'Canada' },
        price: '$30 – $130',
        priceInfo: 'Day passes from $30, full festival pass from $115',
        location: { lat: 51.0782, lng: -114.1289, address: '2500 University Dr NW, Calgary, AB' },
    },
    {
        _id: 'ev47',
        name: 'Newfoundland & Labrador Folk Festival',
        title: 'Newfoundland & Labrador Folk Festival',
        category: 'Music',
        description: 'The Newfoundland and Labrador Folk Festival is one of Canada\'s oldest and most beloved folk festivals, held every August in Bannerman Park in St. John\'s. For over 50 years, it has celebrated the rich traditional music, dance, and storytelling culture of Newfoundland and Labrador, alongside artists from across Canada and around the world.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLy5fptn1Zrm3rR9bqfirUEEScVCfJmGWBBA&s',
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaBIqQbXWuzxGfZCv2K1XPVjikWIneJly-aQ&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRIHgt-TFoN0A16_Z44w_z3K4-rnWwKK2pnuA&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLy5fptn1Zrm3rR9bqfirUEEScVCfJmGWBBA&s',
        ],
        date: '2025-08-01T14:00:00.000Z',
        startAt: '2025-08-01T14:00:00.000Z',
        endAt: '2025-08-03T22:00:00.000Z',
        venue: { name: 'Bannerman Park', address: 'Bannerman Rd', city: "St. John's", state: 'NL', country: 'Canada' },
        price: '$15 – $45',
        priceInfo: 'Single day from $15, weekend pass from $40',
        location: { lat: 47.5675, lng: -52.7084, address: "Bannerman Rd, St. John's, NL" },
    },
    {
        _id: 'ev48',
        name: 'Montreal en Lumière',
        title: 'Montreal en Lumière',
        category: 'Winter Festival',
        description: 'Montreal en Lumière is one of the world\'s premier winter festivals, transforming Montreal into a dazzling celebration of light, gastronomy, and performing arts every February. The 11-day event features spectacular light installations, outdoor activities on the Quartier des Spectacles esplanade, world-class culinary events with international guest chefs, and nightly concerts.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRIHgt-TFoN0A16_Z44w_z3K4-rnWwKK2pnuA&s',
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFWlc7bPP06d2F8ZGDdIwSd2o8AQIeOz8qMw&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTV48NpIAXpOhEavtdpv5T-5jOij-NjJmLEYk1vPhYOvg&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSuNBn6XS0oycJaWbdnoyoY708v89nulNI2qk2sjYP-ZA&s',
        ],
        date: '2026-02-19T17:00:00.000Z',
        startAt: '2026-02-19T17:00:00.000Z',
        endAt: '2026-03-01T23:00:00.000Z',
        venue: { name: 'Quartier des Spectacles', address: 'Place des Festivals', city: 'Montreal', state: 'QC', country: 'Canada' },
        price: 'Free – $120',
        priceInfo: 'Outdoor activities free, culinary events from $50',
        location: { lat: 45.5088, lng: -73.5630, address: 'Place des Festivals, Montreal, QC' },
    },
    {
        _id: 'ev49',
        name: 'Shaw Festival Niagara-on-the-Lake',
        title: 'Shaw Festival',
        category: 'Theatre & Arts',
        description: 'The Shaw Festival in Niagara-on-the-Lake, Ontario is the second-largest repertory theatre festival in North America and the only theatre company in the world dedicated to the works of George Bernard Shaw and his contemporaries. Running from April to October across four stages, it presents world-class productions in one of Canada\'s most beautiful heritage towns.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReYm8ttNn4i6TzC_uKWeWx3z888tedT2WuDg&s',
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRo6LumQJPr89k69gLm8W-f5fFyKGVf1cqnDg&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKsAoSUIr3ZJDEMgW9j8lbKqbMVJvWQF7mLw&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHpf1Y2atmwnOvzBPvA0-eNKpQUHnGyuPj3Q&s',
        ],
        date: '2025-04-05T14:00:00.000Z',
        startAt: '2025-04-05T14:00:00.000Z',
        endAt: '2025-10-26T21:00:00.000Z',
        venue: { name: 'Festival Theatre', address: '10 Queens Parade', city: 'Niagara-on-the-Lake', state: 'ON', country: 'Canada' },
        price: '$35 – $160',
        priceInfo: 'Rush tickets from $35, regular performances from $65',
        location: { lat: 43.2553, lng: -79.0717, address: '10 Queens Parade, Niagara-on-the-Lake, ON' },
    },
    {
        _id: 'ev50',
        name: 'Vancouver Pride Festival',
        title: 'Vancouver Pride Festival',
        category: 'Cultural Festival',
        description: 'Vancouver Pride is one of Canada\'s largest Pride celebrations, held every August with a week of events culminating in the spectacular Pride Parade through downtown Vancouver. The festival features concerts, community events, film screenings, the famous Sunset Beach festival grounds, and the beloved parade drawing hundreds of thousands of participants and spectators along Robson Street.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQiqaXeVa7pzq60fU4ex-AE3gpU85D2uUeDqQ&s',
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQiqaXeVa7pzq60fU4ex-AE3gpU85D2uUeDqQ&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxSubRmc95ZVIKJtiWbn5kRacovanYuhcm5g&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRoHNIO_289Kn8v4VYK-rfHjQ3z8-d5MN21yw&s',
        ],
        date: '2025-07-27T10:00:00.000Z',
        startAt: '2025-07-27T10:00:00.000Z',
        endAt: '2025-08-03T22:00:00.000Z',
        venue: { name: 'Sunset Beach & Downtown Vancouver', address: '1204 Beach Ave', city: 'Vancouver', state: 'BC', country: 'Canada' },
        price: 'Free – $40',
        priceInfo: 'Parade free, festival grounds ticketed from $20',
        location: { lat: 49.2810, lng: -123.1448, address: '1204 Beach Ave, Vancouver, BC' },
    },
    {
        _id: 'ev51',
        name: 'Harvest Jazz & Blues Festival',
        title: 'Harvest Jazz & Blues Festival',
        category: 'Music',
        description: 'The Harvest Jazz & Blues Festival is Atlantic Canada\'s premier music festival, held every September in the beautiful Saint John River valley city of Fredericton, New Brunswick. The six-day event transforms downtown Fredericton with over 100 performances across indoor and outdoor stages, featuring world-class jazz, blues, soul, and roots artists.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_Rwvvov0SjzIggoEQECsJ7xh2AbA2x7St6w&s',
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRItDqUVx-4_mIVx_hP4KkYdGalYr5g2S9EJA&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdj4neBiyIwlHF4S8GWQOQO5dyUNH8LXWwPg&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQvbY_xWaxgxJu3Cb1RuQpGtDzMitxpkctstQ&s',
        ],
        date: '2025-09-10T18:00:00.000Z',
        startAt: '2025-09-10T18:00:00.000Z',
        endAt: '2025-09-14T23:00:00.000Z',
        venue: { name: 'Downtown Fredericton', address: 'Queen St & Regent St', city: 'Fredericton', state: 'NB', country: 'Canada' },
        price: 'Free – $70',
        priceInfo: 'Street stages free, club shows from $25',
        location: { lat: 45.9636, lng: -66.6431, address: 'Queen St, Fredericton, NB' },
    },
    {
        _id: 'ev52',
        name: 'Pender Harbour Jazz Festival',
        title: 'Pender Harbour Jazz Festival',
        category: 'Music',
        description: 'The Pender Harbour Jazz Festival is one of BC\'s most unique and intimate music festivals, held every September in the stunning coastal community of Pender Harbour on the Sunshine Coast. The four-day festival features world-class jazz artists performing in small venues, on boats, and at waterfront stages surrounded by the breathtaking scenery of the BC coast.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRoHNIO_289Kn8v4VYK-rfHjQ3z8-d5MN21yw&s',
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLDqrFFw0P69T8fTRNcPlmHCxBYxBai4p5AA&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwvFvEAks3g2gfNeelRIFsyar7rl0WlnypYw&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLc0gSy2XggTOEOM9UJTlDUT4SLLo3SrBlvTcRUuzPlw&s',
        ],
        date: '2025-09-12T14:00:00.000Z',
        startAt: '2025-09-12T14:00:00.000Z',
        endAt: '2025-09-14T22:00:00.000Z',
        venue: { name: 'Pender Harbour Community Hall', address: 'Garden Bay Rd', city: 'Pender Harbour', state: 'BC', country: 'Canada' },
        price: '$25 – $85',
        priceInfo: 'Single shows from $25, weekend pass from $75',
        location: { lat: 49.6231, lng: -124.0317, address: 'Garden Bay Rd, Pender Harbour, BC' },
    },
    {
        _id: 'ev53',
        name: 'Big Valley Jamboree',
        title: 'Big Valley Jamboree',
        category: 'Music',
        description: 'Big Valley Jamboree is Western Canada\'s largest country music festival, held every August in Camrose, Alberta. The four-day camping festival draws over 100,000 country music fans with a star-studded lineup of top country artists on a massive main stage. It is famous for its incredible community atmosphere, camping culture, and non-stop entertainment.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdJ1-CwSb0rU_X7c-fuTywB9ObpjfVR0-BnQ&s',
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaBIqQbXWuzxGfZCv2K1XPVjikWIneJly-aQ&s',
            'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=800',
            'https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=800',
        ],
        date: '2025-07-31T15:00:00.000Z',
        startAt: '2025-07-31T15:00:00.000Z',
        endAt: '2025-08-03T23:30:00.000Z',
        venue: { name: 'Camrose Exhibition Grounds', address: '4250 Exhibition Dr', city: 'Camrose', state: 'AB', country: 'Canada' },
        price: '$130 – $320',
        priceInfo: 'Single day from $130, 4-day pass from $285',
        location: { lat: 53.0178, lng: -112.8271, address: '4250 Exhibition Dr, Camrose, AB' },
    },
    {
        _id: 'ev54',
        name: 'Festival du Voyageur Winnipeg',
        title: 'Festival du Voyageur',
        category: 'Cultural Festival',
        description: 'Festival du Voyageur is Western Canada\'s largest winter festival and the biggest French-language festival in Western Canada, held every February in Winnipeg\'s historic Saint-Boniface neighbourhood. The 10-day celebration honours the Métis and French-Canadian fur trade heritage with snow sculptures, outdoor concerts, traditional food, and festive activities in a magical winter setting.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS5PQlwqALcKAQOlUZo44Vu15BjOB_cMD5lrQ&s',
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_0TH-nqfbvhWUs1ZZa23jc2Q1Lux12lCieQ&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDPJnw9E_lX79Q4dh1JecQ-6IZgtp-jGZRIQ&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMAbZahLcvlT-1tsYkuc96A3IsbXl-O0xHCA&s',
        ],
        date: '2026-02-13T10:00:00.000Z',
        startAt: '2026-02-13T10:00:00.000Z',
        endAt: '2026-02-22T22:00:00.000Z',
        venue: { name: 'Voyageur Park, Saint-Boniface', address: '768 Taché Ave', city: 'Winnipeg', state: 'MB', country: 'Canada' },
        price: '$15 – $30',
        priceInfo: 'Adults $15, children under 6 free, evening concerts extra',
        location: { lat: 49.8836, lng: -97.1220, address: '768 Taché Ave, Winnipeg, MB' },
    },
    {
        _id: 'ev55',
        name: 'Canadian Music Week Toronto',
        title: 'Canadian Music Week',
        category: 'Music',
        description: 'Canadian Music Week is one of the most important music industry events in Canada, held every May in Toronto. The week-long festival combines a major music industry conference with hundreds of live performances across 30+ venues throughout the city. It showcases emerging and established Canadian and international artists while connecting industry professionals from around the world.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5fJNY2hzzAC8nhg2gEKJS1PwHPj_bWTSBvg&s',
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTrLALZzMw4dHZNWCqjOI0Vt4Y5OEkLnc2e8A&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxzXeRqMr1V9GHVvCace9diA6ow-Oh0MvOhA&s',
            'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800',
        ],
        date: '2025-05-05T18:00:00.000Z',
        startAt: '2025-05-05T18:00:00.000Z',
        endAt: '2025-05-11T02:00:00.000Z',
        venue: { name: 'Multiple Venues, Downtown Toronto', address: 'Yonge St & Dundas St', city: 'Toronto', state: 'ON', country: 'Canada' },
        price: '$25 – $99',
        priceInfo: 'Wristband from $25, industry conference passes separate',
        location: { lat: 43.6561, lng: -79.3802, address: 'Yonge St & Dundas St, Toronto, ON' },
    },
];