import { Restaurant, RestaurantDetail } from '@/domains/restaurants/types';


// ─────────────────────────────────────────────
// REAL CANADIAN EVENTS MOCK DATA
// These are real recurring annual events in Canada.
// Fields match the Event type used in useEvents.ts:
// _id, name, title, category, description,
// imageUrl, images, date, startAt, endAt,
// venue, price, priceInfo, location
// ─────────────────────────────────────────────
export const mockEvents = [
    {
        _id: 'ev1',
        name: 'Toronto International Film Festival',
        title: 'Toronto International Film Festival',
        category: 'Film & Arts',
        description: 'One of the most prestigious film festivals in the world. TIFF brings together thousands of films, industry professionals, and movie lovers from across the globe to Toronto every September. World premieres, galas, and public screenings take place across downtown Toronto venues.',
        imageUrl:   'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwCiLh17MJaRxddacGHQdqPHel3svONlDELQ&s' ,
        images: [
                       'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxzXeRqMr1V9GHVvCace9diA6ow-Oh0MvOhA&s',      
             'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrE0gSiY9U53V0JRQlmcM4-Q2-vXZL6M8hoQ&s   ',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwCiLh17MJaRxddacGHQdqPHel3svONlDELQ&s ',
        ],
        date: '2025-09-04T09:00:00.000Z',
        startAt: '2025-09-04T09:00:00.000Z',
        endAt: '2025-09-14T23:00:00.000Z',
        venue: { name: 'TIFF Bell Lightbox', address: '350 King St W', city: 'Toronto', state: 'ON', country: 'Canada' },
        price: '$25 – $150',
        priceInfo: '$25 – $150 per screening',
        location: { lat: 43.6452, lng: -79.3907, address: '350 King St W, Toronto, ON' },
    },
    {
        _id: 'ev2',
        name: 'Montreal Jazz Festival',
        title: 'Montreal Jazz Festival',
        category: 'Music',
        description: 'The Montreal International Jazz Festival is the largest jazz festival in the world, recognized by the Guinness World Records. Held annually in late June and early July, it features over 500 concerts, with hundreds of free outdoor performances in the heart of downtown Montreal.',
        imageUrl:             'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_Rwvvov0SjzIggoEQECsJ7xh2AbA2x7St6w&s',

        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0xjT2tUuZvHJzNfNW4C7AgKcyrXX1TWuvMw&s',
            ' https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSUFMj5CKSZhD5ysgvOod-sqgwdsdX438GSxA&s ',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_Rwvvov0SjzIggoEQECsJ7xh2AbA2x7St6w&s'
        ],
        date: '2025-06-26T17:00:00.000Z',
        startAt: '2025-06-26T17:00:00.000Z',
        endAt: '2025-07-05T23:59:00.000Z',
        venue: { name: 'Quartier des Spectacles', address: 'Place des Arts', city: 'Montreal', state: 'QC', country: 'Canada' },
        price: 'Free – $120',
        priceInfo: 'Outdoor concerts free, indoor ticketed from $30',
        location: { lat: 45.5088, lng: -73.5630, address: 'Place des Arts, Montreal, QC' },
    },
    {
        _id: 'ev3',
        name: 'Calgary Stampede',
        title: 'Calgary Stampede',
        category: 'Cultural Festival',
        description: 'Known as The Greatest Outdoor Show on Earth, the Calgary Stampede is a world-famous rodeo, exhibition, and festival held every July. It features chuck wagon races, rodeo competitions, midway rides, live music, Indigenous cultural displays, and the famous Stampede Breakfast — all free pancake breakfasts held across the city.',
        imageUrl:        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMAbZahLcvlT-1tsYkuc96A3IsbXl-O0xHCA&s' ,
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMAbZahLcvlT-1tsYkuc96A3IsbXl-O0xHCA&s',
       'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMAbZahLcvlT-1tsYkuc96A3IsbXl-O0xHCA&s' ,
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDPJnw9E_lX79Q4dh1JecQ-6IZgtp-jGZRIQ&s',
        ],
        date: '2025-07-04T08:00:00.000Z',
        startAt: '2025-07-04T08:00:00.000Z',
        endAt: '2025-07-13T23:00:00.000Z',
        venue: { name: 'Stampede Park', address: '1410 Olympic Way SE', city: 'Calgary', state: 'AB', country: 'Canada' },
        price: '$20 – $80',
        priceInfo: 'General admission from $20, rodeo tickets from $45',
        location: { lat: 51.0375, lng: -114.0509, address: '1410 Olympic Way SE, Calgary, AB' },
    },
    {
        _id: 'ev4',
        name: 'Canada Day Celebrations Ottawa',
        title: 'Canada Day Celebrations Ottawa',
        category: 'National Holiday',
        description: 'Canada\'s capital hosts the biggest Canada Day celebration in the country. Parliament Hill comes alive with live concerts, cultural performances, citizenship ceremonies, and the spectacular evening fireworks show over the Ottawa River. Free and open to all, it draws hundreds of thousands of visitors every July 1st.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_0TZBSSV-XldDfpL281rTFD6JwUMlBArsqg&s  ',
        images: [
            '',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_0TZBSSV-XldDfpL281rTFD6JwUMlBArsqg&s  ',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMAbZahLcvlT-1tsYkuc96A3IsbXl-O0xHCA&s' ,
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDPJnw9E_lX79Q4dh1JecQ-6IZgtp-jGZRIQ&s',
        ],
        date: '2025-07-01T10:00:00.000Z',
        startAt: '2025-07-01T10:00:00.000Z',
        endAt: '2025-07-01T23:30:00.000Z',
        venue: { name: 'Parliament Hill', address: 'Wellington St', city: 'Ottawa', state: 'ON', country: 'Canada' },
        price: 'Free',
        priceInfo: 'Free admission — open to all',
        location: { lat: 45.4236, lng: -75.7009, address: 'Wellington St, Ottawa, ON' },
    },
  
    {
        _id: 'ev7',
        name: 'Winterlude Ottawa',
        title: 'Winterlude Ottawa',
        category: 'Winter Festival',
        description: 'Winterlude is Canada\'s national winter festival, held in Ottawa and Gatineau every February. Highlights include skating on the UNESCO World Heritage Rideau Canal — the world\'s largest naturally frozen skating rink — plus elaborate ice sculptures, snow slides, live performances, and family activities across multiple sites.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDPJnw9E_lX79Q4dh1JecQ-6IZgtp-jGZRIQ&s',
        images: [
           'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDPJnw9E_lX79Q4dh1JecQ-6IZgtp-jGZRIQ&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDPJnw9E_lX79Q4dh1JecQ-6IZgtp-jGZRIQ&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDPJnw9E_lX79Q4dh1JecQ-6IZgtp-jGZRIQ&s',
        ],
        date: '2026-01-30T09:00:00.000Z',
        startAt: '2026-01-30T09:00:00.000Z',
        endAt: '2026-02-16T21:00:00.000Z',
        venue: { name: 'Rideau Canal & Confederation Park', address: 'Queen Elizabeth Driveway', city: 'Ottawa', state: 'ON', country: 'Canada' },
        price: 'Free',
        priceInfo: 'Free — skate rentals available on site',
        location: { lat: 45.4112, lng: -75.6898, address: 'Queen Elizabeth Driveway, Ottawa, ON' },
    },
   
    {
        _id: 'ev11',
        name: 'Quebec Winter Carnival',
        title: 'Quebec Winter Carnival',
        category: 'Winter Festival',
        description: 'The Quebec City Winter Carnival is the world\'s largest winter carnival, held every February. Bonhomme Carnaval, the iconic snowman mascot, hosts events including the famous Ice Palace, night parades, canoe races across the St. Lawrence River, snow sculptures, ice slides, and the popular Carnival outdoor bars with traditional caribou cocktail.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFWlc7bPP06d2F8ZGDdIwSd2o8AQIeOz8qMw&s',
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTV48NpIAXpOhEavtdpv5T-5jOij-NjJmLEYk1vPhYOvg&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSuNBn6XS0oycJaWbdnoyoY708v89nulNI2qk2sjYP-ZA&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMT1GCN0uYJJbs62NlAr2nQdbtV_V15y2Aaw&s',
        ],
        date: '2026-01-29T10:00:00.000Z',
        startAt: '2026-01-29T10:00:00.000Z',
        endAt: '2026-02-15T22:00:00.000Z',
        venue: { name: 'Old Quebec City', address: 'Plains of Abraham & Old Port', city: 'Quebec City', state: 'QC', country: 'Canada' },
        price: '$22 – $28',
        priceInfo: 'Effigy (pass) $22 adults, children under 12 free',
        location: { lat: 46.8139, lng: -71.2082, address: 'Plains of Abraham, Quebec City, QC' },
    },
    {
        _id: 'ev12',
        name: 'Vancouver Cherry Blossom Festival',
        title: 'Vancouver Cherry Blossom Festival',
        category: 'Nature & Cultural',
        description: 'The Vancouver Cherry Blossom Festival celebrates the blooming of over 40,000 cherry trees across the city every spring. Events include the Haiku Invitational, Big Picnic under the blossoms, tree tours, art installations, and cultural performances. Stanley Park and Queen Elizabeth Park offer spectacular blossom viewing.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRoHNIO_289Kn8v4VYK-rfHjQ3z8-d5MN21yw&s',
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLc0gSy2XggTOEOM9UJTlDUT4SLLo3SrBlvTcRUuzPlw&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHpf1Y2atmwnOvzBPvA0-eNKpQUHnGyuPj3Q&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwvFvEAks3g2gfNeelRIFsyar7rl0WlnypYw&s',
        ],
        date: '2026-03-21T09:00:00.000Z',
        startAt: '2026-03-21T09:00:00.000Z',
        endAt: '2026-04-20T20:00:00.000Z',
        venue: { name: 'Stanley Park & City-wide', address: 'Stanley Park', city: 'Vancouver', state: 'BC', country: 'Canada' },
        price: 'Free – $35',
        priceInfo: 'Most events free, Big Picnic tickets from $35',
        location: { lat: 49.3043, lng: -123.1443, address: 'Stanley Park, Vancouver, BC' },
    },
    {
        _id: 'ev13',
        name: 'Toronto Pride Festival',
        title: 'Toronto Pride Festival',
        category: 'Cultural Festival',
        description: 'Toronto Pride is one of the largest Pride festivals in the world, drawing over one million participants every June. The 10-day celebration includes the legendary Pride Parade on Yonge Street, Trans March, Dyke March, film festival, concerts, community events, and the iconic street fair on Church Street. It is a powerful celebration of love, diversity, and inclusion.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQiqaXeVa7pzq60fU4ex-AE3gpU85D2uUeDqQ&s',
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSrcmqsodyXaSbop8zA59lNgBVD4kiI9OTfNGIwPha0VQ&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSuNBn6XS0oycJaWbdnoyoY708v89nulNI2qk2sjYP-ZA&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMT1GCN0uYJJbs62NlAr2nQdbtV_V15y2Aaw&s',
        ],
        date: '2025-06-20T10:00:00.000Z',
        startAt: '2025-06-20T10:00:00.000Z',
        endAt: '2025-06-29T23:00:00.000Z',
        venue: { name: 'Church-Wellesley Village', address: 'Church St & Wellesley St', city: 'Toronto', state: 'ON', country: 'Canada' },
        price: 'Free',
        priceInfo: 'Free — ticketed concerts available separately',
        location: { lat: 43.6654, lng: -79.3818, address: 'Church St, Toronto, ON' },
    },
    {
        _id: 'ev14',
        name: 'Edmonton Folk Music Festival',
        title: 'Edmonton Folk Music Festival',
        category: 'Music',
        description: 'The Edmonton Folk Music Festival is one of Canada\'s best-loved outdoor music festivals, held every August in the beautiful Gallagher Park overlooking the North Saskatchewan River valley. The four-day festival features artists from folk, roots, blues, bluegrass, country, and world music traditions on multiple stages.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaBIqQbXWuzxGfZCv2K1XPVjikWIneJly-aQ&s',
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSuNBn6XS0oycJaWbdnoyoY708v89nulNI2qk2sjYP-ZA&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMT1GCN0uYJJbs62NlAr2nQdbtV_V15y2Aaw&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwvFvEAks3g2gfNeelRIFsyar7rl0WlnypYw&s',
        ],
        date: '2025-08-07T12:00:00.000Z',
        startAt: '2025-08-07T12:00:00.000Z',
        endAt: '2025-08-10T22:30:00.000Z',
        venue: { name: 'Gallagher Park', address: '9310 98 Ave NW', city: 'Edmonton', state: 'AB', country: 'Canada' },
        price: '$50 – $240',
        priceInfo: 'Single day from $50, full weekend passes from $195',
        location: { lat: 53.5283, lng: -113.4735, address: '9310 98 Ave NW, Edmonton, AB' },
    },
    {
        _id: 'ev15',
        name: 'Nuit Blanche Toronto',
        title: 'Nuit Blanche Toronto',
        category: 'Arts & Culture',
        description: 'Nuit Blanche is a free all-night contemporary art event transforming Toronto\'s streets, parks, and public spaces from dusk to dawn every fall. Hundreds of art installations, performances, and exhibitions take over the city, with participation from local and international artists. It is one of the most attended free art events in North America.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRwSlfVPT01EH3Ik-fRXG9FXpmRkTVexrdjg&s',
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSuNBn6XS0oycJaWbdnoyoY708v89nulNI2qk2sjYP-ZA&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMT1GCN0uYJJbs62NlAr2nQdbtV_V15y2Aaw&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwvFvEAks3g2gfNeelRIFsyar7rl0WlnypYw&s',
        ],
        date: '2025-10-04T19:00:00.000Z',
        startAt: '2025-10-04T19:00:00.000Z',
        endAt: '2025-10-05T07:00:00.000Z',
        venue: { name: 'Downtown Toronto (City-wide)', address: 'Nathan Phillips Square & Surroundings', city: 'Toronto', state: 'ON', country: 'Canada' },
        price: 'Free',
        priceInfo: 'Completely free — no tickets required',
        location: { lat: 43.6529, lng: -79.3849, address: 'Nathan Phillips Square, Toronto, ON' },
    },
    {
        _id: 'ev16',
        name: 'Banff Mountain Film and Book Festival',
        title: 'Banff Mountain Film and Book Festival',
        category: 'Film & Adventure',
        description: 'The Banff Centre Mountain Film and Book Festival is the world\'s premier mountain culture event, held every November in the stunning Rocky Mountain town of Banff. It showcases the best mountain, adventure, and exploration films from around the world, alongside award-winning mountain literature and speakers.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXR_hRAfUVwAHvTAQmqZ6chPFIhnLsFIIOhA&s',
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHpf1Y2atmwnOvzBPvA0-eNKpQUHnGyuPj3Q&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSuNBn6XS0oycJaWbdnoyoY708v89nulNI2qk2sjYP-ZA&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMT1GCN0uYJJbs62NlAr2nQdbtV_V15y2Aaw&s',
        ],
        date: '2025-10-25T09:00:00.000Z',
        startAt: '2025-10-25T09:00:00.000Z',
        endAt: '2025-11-02T22:00:00.000Z',
        venue: { name: 'Banff Centre for Arts and Creativity', address: '107 Tunnel Mountain Dr', city: 'Banff', state: 'AB', country: 'Canada' },
        price: '$20 – $60',
        priceInfo: 'Single screenings from $20, passes from $150',
        location: { lat: 51.1794, lng: -115.5708, address: '107 Tunnel Mountain Dr, Banff, AB' },
    },
    {
        _id: 'ev17',
        name: 'Halifax Seafood Festival',
        title: 'Halifax Seafood Festival',
        category: 'Food & Drink',
        description: 'The Halifax Lobster Crawl and Seafood Festival celebrates Nova Scotia\'s incredible seafood culture every February. Restaurants, fishermen, and food lovers come together for lobster dinners, seafood tastings, cooking demonstrations, and harbour tours. It is the perfect celebration of Atlantic Canada\'s most prized culinary treasures.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTl3jp9WSIuPEVoZY2Zk0DPgnSw4dYmvKpc-w&s',
        images: [
            'https://images.unsplash.com/photo-1559847844-5315695dadae?w=800',
            'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800',
            'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800',
        ],
        date: '2026-02-06T11:00:00.000Z',
        startAt: '2026-02-06T11:00:00.000Z',
        endAt: '2026-02-16T21:00:00.000Z',
        venue: { name: 'Halifax Waterfront', address: 'Lower Water St', city: 'Halifax', state: 'NS', country: 'Canada' },
        price: '$35 – $120',
        priceInfo: 'Lobster dinner events from $35 per person',
        location: { lat: 44.6476, lng: -63.5728, address: 'Lower Water St, Halifax, NS' },
    },
    {
        _id: 'ev18',
        name: 'Ottawa Bluesfest',
        title: 'Ottawa Bluesfest',
        category: 'Music',
        description: 'Ottawa Bluesfest is one of the largest music festivals in Canada and the largest blues festival in North America. Held every July at LeBreton Flats Park near the Ottawa River, it features over 100 artists across multiple stages over 10 days, spanning blues, rock, pop, folk, hip-hop, and world music.',
        imageUrl: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=800',
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQvbY_xWaxgxJu3Cb1RuQpGtDzMitxpkctstQ&s',
            'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800',
            'https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=800',
        ],
        date: '2025-07-04T16:00:00.000Z',
        startAt: '2025-07-04T16:00:00.000Z',
        endAt: '2025-07-13T23:30:00.000Z',
        venue: { name: 'LeBreton Flats Park', address: 'Fleet St', city: 'Ottawa', state: 'ON', country: 'Canada' },
        price: '$30 – $180',
        priceInfo: 'Single day from $30, full festival pass from $150',
        location: { lat: 45.4201, lng: -75.7197, address: 'Fleet St, Ottawa, ON' },
    },
    {
        _id: 'ev19',
        name: 'Taste of the Danforth Toronto',
        title: 'Taste of the Danforth Toronto',
        category: 'Food & Drink',
        description: 'Taste of the Danforth is North America\'s largest Greek street festival, held every August along Danforth Avenue in Toronto\'s Greektown. Over 1.6 million people attend to enjoy authentic Greek food, live music on multiple stages, dancing, and cultural activities. The three-day event transforms the street into a massive outdoor celebration.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjTQGNg14bQBdxh8ydBtTzr3IDDQmpTAox0g&s',
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQv4asVgruM8wmW0oyWefUb7sHiGk44IgHNtg&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMT1GCN0uYJJbs62NlAr2nQdbtV_V15y2Aaw&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwvFvEAks3g2gfNeelRIFsyar7rl0WlnypYw&s',
        ],
        date: '2025-08-08T11:00:00.000Z',
        startAt: '2025-08-08T11:00:00.000Z',
        endAt: '2025-08-10T23:00:00.000Z',
        venue: { name: 'Danforth Avenue (Greektown)', address: 'Danforth Ave between Broadview and Jones', city: 'Toronto', state: 'ON', country: 'Canada' },
        price: 'Free',
        priceInfo: 'Free entry — food and drink purchased separately',
        location: { lat: 43.6789, lng: -79.3517, address: 'Danforth Ave, Toronto, ON' },
    },
    {
        _id: 'ev20',
        name: 'Whistler Film Festival',
        title: 'Whistler Film Festival',
        category: 'Film & Arts',
        description: 'The Whistler Film Festival is Canada\'s premier destination film festival, held every December in the mountain resort town of Whistler, BC. It showcases Canadian and international films through screenings, industry panels, and the prestigious Whistler Film Awards, all set against the backdrop of the stunning Whistler Blackcomb mountains.',
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7jjop_P0ggCoiEQU8cDY_d0agNIk80ps7Cw&s',
        images: [
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwvFvEAks3g2gfNeelRIFsyar7rl0WlnypYw&s',
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMT1GCN0uYJJbs62NlAr2nQdbtV_V15y2Aaw&s',
            'https://images.unsplash.com/photo-1524985069026-dd778a71c7b4?w=800',
        ],
        date: '2025-12-03T10:00:00.000Z',
        startAt: '2025-12-03T10:00:00.000Z',
        endAt: '2025-12-07T22:00:00.000Z',
        venue: { name: 'Whistler Conference Centre', address: '4010 Whistler Way', city: 'Whistler', state: 'BC', country: 'Canada' },
        price: '$15 – $45',
        priceInfo: 'Single screenings from $15, passes from $99',
        location: { lat: 50.1163, lng: -122.9574, address: '4010 Whistler Way, Whistler, BC' },
    },
];
