export const useTheme = () => ({
    bg: '#FFF9F1',
    card: '#FFFBFA',
    text: '#111827',
    subtext: '#6b7280',
    border: '#f3f4f6',
    inputBg: '#ffffff',
    inputText: '#111827',
    inputPlaceholder: '#9ca3af',
    chipBg: '#FFF5E6',
    chipBorder: '#FFE0C7',
    chipText: '#FF7A00',
    sectionLabel: '#374151',
    headerBgRestaurant: '#FFF5E6',
    headerBgTiffin: '#f5efe8',
    headerBgEvents: '#efe9f6',
    headerBgSettings: '#FFF5E6',
    headerCircleRestaurant: '#FFE0C7',
    headerCircleTiffin: '#efe6db',
    headerCircleEvents: '#e3daf0',
    headerCircleSettings: '#FFE0C7',
});
