import { Restaurant, RestaurantDetail } from '@/domains/restaurants/types';

// ─────────────────────────────────────────────
// REAL CANADIAN VEG RESTAURANTS MOCK DATA
// ─────────────────────────────────────────────
export const mockFeaturedRestaurants: Restaurant[] = [
    {
        _id: 'fr1',
        name: 'The Acorn',
        description: 'Vancouver\'s celebrated plant-forward fine dining — creative seasonal vegetarian cuisine on Main Street. Award-winning dishes using locally sourced BC produce.',
        cuisineTags: ['Vegetarian', 'Fine Dining', 'Seasonal', 'West Coast'],
        cuisines: ['Vegetarian', 'Fine Dining'],
        priceRange: '$$$',
        badges: ['Award Winning', 'Fine Dining'],
        serviceTypes: ['Dine-in'],
        vegOnly: true,
        isVeg: true,
        rating: 4.7,
        images: [
            'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
            'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
            'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?w=800',
        ],
        imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
        location: { lat: 49.2630, lng: -123.1014, address: '3995 Main St, Vancouver, BC' },
        address: '3995 Main St, Vancouver, BC',
        hasOffer: false,
        features: ['Tasting Menu', 'Wine Pairing', 'Seasonal Menu'],
        opening_hours: { 'Tue-Sun': '5pm - 10pm', 'Mon': 'Closed' },
    },
    {
        _id: 'fr2',
        name: 'Fresh Restaurant',
        description: 'Toronto\'s iconic vegetarian restaurant since 1999 — vibrant bowls, smoothies and plant-based comfort food loved by locals and visitors alike.',
        cuisineTags: ['Vegetarian', 'Healthy', 'Canadian', 'Smoothies'],
        cuisines: ['Vegetarian', 'Healthy'],
        priceRange: '$$',
        badges: ['Toronto Icon', 'Healthy'],
        serviceTypes: ['Dine-in', 'Takeaway', 'Delivery'],
        vegOnly: true,
        isVeg: true,
        rating: 4.6,
        images: [
            'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800',
            'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800',
            'https://images.unsplash.com/photo-1547592180-85f173990554?w=800',
        ],
        imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800',
        location: { lat: 43.6629, lng: -79.3957, address: '326 Bloor St W, Toronto, ON' },
        address: '326 Bloor St W, Toronto, ON',
        hasOffer: false,
        features: ['Smoothie Bar', 'Brunch', 'Outdoor Seating'],
        opening_hours: { 'Mon-Sun': '9am - 10pm' },
    },
    {
        _id: 'fr3',
        name: 'Copper Branch',
        description: 'Canada\'s largest plant-based fast food chain — nourishing bowls, burgers and wraps made entirely from plants, with locations across the country.',
        cuisineTags: ['Vegan', 'Plant-Based', 'Fast Food', 'Healthy'],
        cuisines: ['Vegan', 'Plant-Based'],
        priceRange: '$$',
        badges: ['Vegan', 'Popular', 'Canada-Wide'],
        serviceTypes: ['Dine-in', 'Takeaway', 'Delivery'],
        vegOnly: true,
        isVeg: true,
        rating: 4.4,
        images: [
            'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800',
            'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
            'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800',
        ],
        imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800',
        location: { lat: 45.5017, lng: -73.5673, address: '1204 Avenue McGill College, Montreal, QC' },
        address: '1204 Avenue McGill College, Montreal, QC',
        hasOffer: true,
        offer: '10% off bowls on Mondays',
        features: ['Vegan', 'Takeout', 'Quick Bite'],
        opening_hours: { 'Mon-Sun': '10am - 9pm' },
    },
    {
        _id: 'fr4',
        name: 'Planta Queen',
        description: 'Toronto\'s stunning plant-based Asian fusion restaurant — dim sum, ramen and sushi reinvented without animal products in a beautiful King West space.',
        cuisineTags: ['Vegan', 'Asian Fusion', 'Japanese', 'Dim Sum'],
        cuisines: ['Vegan', 'Asian Fusion'],
        priceRange: '$$$',
        badges: ['Vegan', 'Trendy', 'Asian Fusion'],
        serviceTypes: ['Dine-in', 'Takeaway'],
        vegOnly: true,
        isVeg: true,
        rating: 4.6,
        images: [
            'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=800',
            'https://images.unsplash.com/photo-1547592180-85f173990554?w=800',
            'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800',
        ],
        imageUrl: 'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=800',
        location: { lat: 43.6481, lng: -79.3991, address: '180 Queen St W, Toronto, ON' },
        address: '180 Queen St W, Toronto, ON',
        hasOffer: false,
        features: ['Cocktail Bar', 'Group Dining', 'Brunch'],
        opening_hours: { 'Mon-Sun': '12pm - 11pm' },
    },
    {
        _id: 'fr5',
        name: 'Aux Vivres',
        description: 'Montreal\'s landmark vegan diner since 1997 — hearty comfort food, brunch classics and famous dragon bowls that have fed generations of Montrealers.',
        cuisineTags: ['Vegan', 'Diner', 'Brunch', 'Canadian'],
        cuisines: ['Vegan', 'Canadian'],
        priceRange: '$$',
        badges: ['Montreal Icon', 'Vegan', 'Since 1997'],
        serviceTypes: ['Dine-in', 'Takeaway', 'Delivery'],
        vegOnly: true,
        isVeg: true,
        rating: 4.5,
        images: [
            'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=800',
            'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?w=800',
            'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
        ],
        imageUrl: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=800',
        location: { lat: 45.5235, lng: -73.5972, address: '4631 St-Laurent Blvd, Montreal, QC' },
        address: '4631 St-Laurent Blvd, Montreal, QC',
        hasOffer: true,
        offer: 'Brunch special $16 with coffee Sat-Sun',
        features: ['Brunch', 'Delivery', 'Takeout'],
        opening_hours: { 'Mon-Sun': '9am - 10pm' },
    },
    {
        _id: 'fr6',
        name: 'Vedge Indian Bistro',
        description: 'Pure vegetarian Indian restaurant in Calgary serving authentic curries, biryanis and street food with no compromise on flavour or tradition.',
        cuisineTags: ['Pure Veg', 'Indian', 'Vegetarian', 'Curry'],
        cuisines: ['Indian', 'Vegetarian'],
        priceRange: '$$',
        badges: ['Pure Veg', 'Authentic Indian'],
        serviceTypes: ['Dine-in', 'Takeaway', 'Delivery'],
        vegOnly: true,
        isVeg: true,
        rating: 4.5,
        images: [
            'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800',
            'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800',
            'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
        ],
        imageUrl: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800',
        location: { lat: 51.0447, lng: -114.0719, address: '940 6 Ave SW, Calgary, AB' },
        address: '940 6 Ave SW, Calgary, AB',
        hasOffer: true,
        offer: 'Lunch thali $14.99 Mon-Fri',
        features: ['Delivery', 'Family Friendly', 'Takeout'],
        opening_hours: { 'Mon-Sun': '11am - 10pm' },
    },
    {
        _id: 'fr7',
        name: 'Virtuous Pie',
        description: 'Vancouver and Toronto plant-based pizzeria — creative vegan pies with cashew cheese and seasonal toppings. One of Canada\'s most celebrated vegan chains.',
        cuisineTags: ['Vegan', 'Pizza', 'Italian', 'Plant-Based'],
        cuisines: ['Vegan', 'Pizza'],
        priceRange: '$$',
        badges: ['Vegan', 'Popular', 'Multiple Locations'],
        serviceTypes: ['Dine-in', 'Takeaway', 'Delivery'],
        vegOnly: true,
        isVeg: true,
        rating: 4.5,
        images: [
            'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800',
            'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800',
            'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800',
        ],
        imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800',
        location: { lat: 49.2802, lng: -123.1187, address: '583 Hastings St, Vancouver, BC' },
        address: '583 Hastings St, Vancouver, BC',
        hasOffer: true,
        offer: 'Happy hour slices $5 daily 3-5pm',
        features: ['Vegan', 'Takeout', 'Late Night'],
        opening_hours: { 'Mon-Sun': '11:30am - 10pm' },
    },
    {
        _id: 'fr8',
        name: 'The Green Door',
        description: 'Ottawa\'s beloved vegetarian buffet restaurant — pay by weight, all fresh, all made in-house since 1988. A true Ottawa institution loved by the community.',
        cuisineTags: ['Vegetarian', 'Buffet', 'Healthy', 'Canadian'],
        cuisines: ['Vegetarian', 'Healthy'],
        priceRange: '$',
        badges: ['Ottawa Institution', 'Buffet', 'Since 1988'],
        serviceTypes: ['Dine-in', 'Takeaway'],
        vegOnly: true,
        isVeg: true,
        rating: 4.4,
        images: [
            'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800',
            'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
            'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=800',
        ],
        imageUrl: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800',
        location: { lat: 45.4182, lng: -75.6691, address: '198 Main St, Ottawa, ON' },
        address: '198 Main St, Ottawa, ON',
        hasOffer: false,
        features: ['Buffet', 'Pay by Weight', 'Takeout'],
        opening_hours: { 'Mon-Sat': '11am - 9pm', 'Sun': '10am - 8pm' },
    },
    {
        _id: 'fr9',
        name: 'Nourish Kitchen',
        description: 'Victoria BC plant-based restaurant committed to zero waste — creative vegan bowls and cold-pressed juices using Vancouver Island\'s best local produce.',
        cuisineTags: ['Vegan', 'Healthy', 'Zero Waste', 'West Coast'],
        cuisines: ['Vegan', 'Healthy'],
        priceRange: '$$',
        badges: ['Zero Waste', 'Healthy', 'BC Gem'],
        serviceTypes: ['Dine-in', 'Takeaway'],
        vegOnly: true,
        isVeg: true,
        rating: 4.6,
        images: [
            'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800',
            'https://images.unsplash.com/photo-1547592180-85f173990554?w=800',
            'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800',
        ],
        imageUrl: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800',
        location: { lat: 48.4284, lng: -123.3656, address: '225 Quebec St, Victoria, BC' },
        address: '225 Quebec St, Victoria, BC',
        hasOffer: false,
        features: ['Juice Bar', 'Zero Waste', 'Outdoor Seating'],
        opening_hours: { 'Mon-Sat': '9am - 8pm', 'Sun': '10am - 6pm' },
    },
    {
        _id: 'fr10',
        name: 'Halo Brewery',
        description: 'Toronto vegan brewery and kitchen — plant-based snacks, mains and craft beers brewed on site in the Bloordale Village neighbourhood.',
        cuisineTags: ['Vegan', 'Brewery', 'Canadian', 'Craft Beer'],
        cuisines: ['Vegan', 'Canadian'],
        priceRange: '$$',
        badges: ['Vegan', 'Craft Beer', 'Unique'],
        serviceTypes: ['Dine-in'],
        vegOnly: true,
        isVeg: true,
        rating: 4.4,
        images: [
            'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800',
            'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
            'https://images.unsplash.com/photo-1547592180-85f173990554?w=800',
        ],
        imageUrl: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800',
        location: { lat: 43.6741, lng: -79.3399, address: '247 Wallace Ave, Toronto, ON' },
        address: '247 Wallace Ave, Toronto, ON',
        hasOffer: false,
        features: ['Craft Beer', 'Outdoor Patio', 'Live Events'],
        opening_hours: { 'Wed-Sun': '12pm - 10pm', 'Mon-Tue': 'Closed' },
    },
    {
        _id: 'fr11',
        name: 'Annapurna Vegetarian',
        description: 'Pure vegetarian Indian restaurant in Toronto serving South and North Indian thalis, dosas and curries. A staple of the Annex neighbourhood for decades.',
        cuisineTags: ['Pure Veg', 'Indian', 'Vegetarian', 'South Indian'],
        cuisines: ['Indian', 'Vegetarian'],
        priceRange: '$',
        badges: ['Pure Veg', 'Budget Friendly', 'Authentic'],
        serviceTypes: ['Dine-in', 'Takeaway'],
        vegOnly: true,
        isVeg: true,
        rating: 4.3,
        images: [
            'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800',
            'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800',
            'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
        ],
        imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800',
        location: { lat: 43.6629, lng: -79.3957, address: '1085 Bathurst St, Toronto, ON' },
        address: '1085 Bathurst St, Toronto, ON',
        hasOffer: true,
        offer: 'All-you-can-eat lunch buffet $13.99',
        features: ['Buffet', 'Takeout', 'Family Friendly'],
        opening_hours: { 'Tue-Sun': '11:30am - 9:30pm', 'Mon': 'Closed' },
    },
    {
        _id: 'fr12',
        name: 'Rosewood Vegan Kitchen',
        description: 'Upscale vegan fine dining in Vancouver — seasonal tasting menus made from BC-grown organic produce by Chef Amber Trudeau.',
        cuisineTags: ['Vegan', 'Fine Dining', 'West Coast', 'Seasonal'],
        cuisines: ['Vegan', 'Fine Dining'],
        priceRange: '$$$',
        badges: ['Fine Dining', 'Vegan', 'Award Winning'],
        serviceTypes: ['Dine-in'],
        vegOnly: true,
        isVeg: true,
        rating: 4.8,
        images: [
            'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
            'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800',
            'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
        ],
        imageUrl: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
        location: { lat: 49.2820, lng: -123.1190, address: '620 Seymour St, Vancouver, BC' },
        address: '620 Seymour St, Vancouver, BC',
        hasOffer: false,
        features: ['Tasting Menu', 'Wine Pairing', 'Private Dining'],
        opening_hours: { 'Tue-Sun': '6pm - 10pm', 'Mon': 'Closed' },
    },
    {
        _id: 'fr13',
        name: 'Green Earth Cafe',
        description: 'Ottawa\'s cozy all-day vegetarian cafe — house-baked bread, hearty grain bowls and organic fair-trade coffee in a warm welcoming space.',
        cuisineTags: ['Vegetarian', 'Cafe', 'Healthy', 'Organic'],
        cuisines: ['Vegetarian', 'Cafe'],
        priceRange: '$',
        badges: ['Organic', 'Cozy', 'Brunch Spot'],
        serviceTypes: ['Dine-in', 'Takeaway'],
        vegOnly: true,
        isVeg: true,
        rating: 4.3,
        images: [
            'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800',
            'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
            'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800',
        ],
        imageUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800',
        location: { lat: 45.4215, lng: -75.6919, address: '362 Richmond Rd, Ottawa, ON' },
        address: '362 Richmond Rd, Ottawa, ON',
        hasOffer: true,
        offer: 'Free cookie with any coffee before 10am',
        features: ['Organic', 'Brunch', 'Takeout'],
        opening_hours: { 'Mon-Fri': '7am - 6pm', 'Sat-Sun': '8am - 5pm' },
    },
    {
        _id: 'fr14',
        name: 'Sattvik Indian Vegetarian',
        description: 'Pure veg North Indian thali house in Toronto — rich dal makhani, paneer dishes and freshly baked naans without garlic or onion. Jain-friendly.',
        cuisineTags: ['Pure Veg', 'Indian', 'Vegetarian', 'Jain Friendly'],
        cuisines: ['Indian', 'Vegetarian'],
        priceRange: '$$',
        badges: ['Pure Veg', 'Jain Friendly', 'Authentic'],
        serviceTypes: ['Dine-in', 'Takeaway', 'Delivery'],
        vegOnly: true,
        isVeg: true,
        rating: 4.5,
        images: [
            'https://images.unsplash.com/photo-1631515242808-497c3fbd1571?w=800',
            'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800',
            'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800',
        ],
        imageUrl: 'https://images.unsplash.com/photo-1631515242808-497c3fbd1571?w=800',
        location: { lat: 43.7715, lng: -79.4139, address: '1562 Sandhurst Circle, Toronto, ON' },
        address: '1562 Sandhurst Circle, Toronto, ON',
        hasOffer: true,
        offer: 'Unlimited thali lunch $16.99',
        features: ['Buffet', 'Delivery', 'Family Friendly'],
        opening_hours: { 'Mon-Sun': '11am - 10pm' },
        _isMockData: true,
    } as Restaurant,
    {
        _id: 'fr15',
        name: 'Terrain Vegan Eatery',
        description: 'Montreal\'s earthy plant-based bistro — hearty grain bowls, house-fermented kimchi and cashew cheeses made fresh daily on St-Laurent.',
        cuisineTags: ['Vegan', 'Healthy', 'Fermented', 'Montreal'],
        cuisines: ['Vegan', 'Healthy'],
        priceRange: '$$',
        badges: ['Vegan', 'Healthy', 'Popular'],
        serviceTypes: ['Dine-in', 'Takeaway'],
        vegOnly: true,
        isVeg: true,
        rating: 4.4,
        images: [
            'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
            'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800',
            'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800',
        ],
        imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
        location: { lat: 45.5260, lng: -73.5985, address: '5226 Blvd Saint-Laurent, Montreal, QC' },
        address: '5226 Blvd Saint-Laurent, Montreal, QC',
        hasOffer: true,
        offer: 'Happy hour bowls $12 (4–6pm)',
        features: ['Takeout', 'Quick Bite', 'Outdoor Seating'],
        opening_hours: { 'Mon-Sat': '11am - 9pm', 'Sun': '11am - 7pm' },
        _isMockData: true,
    } as Restaurant,
    {
        _id: 'fr16',
        name: 'Prana Plant Kitchen',
        description: 'Calgary\'s wellness-focused vegan restaurant — cold-pressed juices, adaptogen lattes and macro-balanced plates for the health-conscious diner.',
        cuisineTags: ['Vegan', 'Wellness', 'Healthy', 'Juice Bar'],
        cuisines: ['Vegan', 'Healthy'],
        priceRange: '$$',
        badges: ['Healthy', 'Vegan', 'Wellness'],
        serviceTypes: ['Dine-in', 'Takeaway'],
        vegOnly: true,
        isVeg: true,
        rating: 4.5,
        images: [
            'https://images.unsplash.com/photo-1543362906-acfc16c67564?w=800',
            'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
            'https://images.unsplash.com/photo-1547592180-85f173990554?w=800',
        ],
        imageUrl: 'https://images.unsplash.com/photo-1543362906-acfc16c67564?w=800',
        location: { lat: 51.0390, lng: -114.0638, address: '812 16 Ave SW, Calgary, AB' },
        address: '812 16 Ave SW, Calgary, AB',
        hasOffer: false,
        features: ['Juice Bar', 'Wellness', 'Takeout'],
        opening_hours: { 'Mon-Fri': '8am - 8pm', 'Sat-Sun': '9am - 7pm' },
        _isMockData: true,
    } as Restaurant,
    {
        _id: 'fr17',
        name: 'Saraswati South Indian Veg',
        description: 'Authentic South Indian vegetarian restaurant in Ottawa — masala dosas, idlis, sambar and filter coffee just like you\'d find in Chennai.',
        cuisineTags: ['Pure Veg', 'South Indian', 'Vegetarian', 'Dosa'],
        cuisines: ['South Indian', 'Vegetarian'],
        priceRange: '$',
        badges: ['Pure Veg', 'South Indian', 'Budget Friendly'],
        serviceTypes: ['Dine-in', 'Takeaway'],
        vegOnly: true,
        isVeg: true,
        rating: 4.6,
        images: [
            'https://images.unsplash.com/photo-1630383249896-424e482df921?w=800',
            'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800',
            'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800',
        ],
        imageUrl: 'https://images.unsplash.com/photo-1630383249896-424e482df921?w=800',
        location: { lat: 45.3490, lng: -75.7560, address: '2211 Carling Ave, Ottawa, ON' },
        address: '2211 Carling Ave, Ottawa, ON',
        hasOffer: true,
        offer: 'Dosa combo $11.99 all day',
        features: ['Family Friendly', 'Takeout', 'Quick Bite'],
        opening_hours: { 'Tue-Sun': '11am - 9:30pm', 'Mon': 'Closed' },
        _isMockData: true,
    } as Restaurant,
    {
        _id: 'fr18',
        name: 'Verdure Italian Veg',
        description: 'All-vegetarian Italian trattoria in Toronto — wood-fired pizzas with cashew mozzarella, handmade pasta and tiramisu that prove vegan Italian can be extraordinary.',
        cuisineTags: ['Vegetarian', 'Italian', 'Pizza', 'Pasta'],
        cuisines: ['Vegetarian', 'Italian'],
        priceRange: '$$$',
        badges: ['Vegetarian', 'Italian', 'Trendy'],
        serviceTypes: ['Dine-in', 'Takeaway'],
        vegOnly: true,
        isVeg: true,
        rating: 4.6,
        images: [
            'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800',
            'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800',
            'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800',
        ],
        imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800',
        location: { lat: 43.6551, lng: -79.4000, address: '849 Dundas St W, Toronto, ON' },
        address: '849 Dundas St W, Toronto, ON',
        hasOffer: true,
        offer: 'Pizza night Tuesdays — 2 for 1',
        features: ['Wood-Fired', 'Wine Bar', 'Patio'],
        opening_hours: { 'Tue-Sun': '5pm - 10:30pm', 'Mon': 'Closed' },
        _isMockData: true,
    } as Restaurant,
    {
        _id: 'fr19',
        name: 'Sprout Vegan Deli',
        description: 'Halifax plant-based deli and sandwich bar — smoked carrot lox, cashew cream cheese bagels and chilled wraps to go on Dresden Row.',
        cuisineTags: ['Vegan', 'Deli', 'Sandwiches', 'Breakfast'],
        cuisines: ['Vegan', 'Deli'],
        priceRange: '$',
        badges: ['Vegan', 'Quick Bite', 'Popular'],
        serviceTypes: ['Dine-in', 'Takeaway'],
        vegOnly: true,
        isVeg: true,
        rating: 4.4,
        images: [
            'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800',
            'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?w=800',
            'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800',
        ],
        imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800',
        location: { lat: 44.6488, lng: -63.5752, address: '1569 Dresden Row, Halifax, NS' },
        address: '1569 Dresden Row, Halifax, NS',
        hasOffer: true,
        offer: 'Bagel & coffee combo $9.99 mornings',
        features: ['Quick Bite', 'Takeout', 'Breakfast'],
        opening_hours: { 'Mon-Fri': '7:30am - 5pm', 'Sat': '9am - 4pm', 'Sun': 'Closed' },
        _isMockData: true,
    } as Restaurant,
    {
        _id: 'fr20',
        name: 'Govinda\'s Pure Veg',
        description: 'Community-run Hare Krishna vegetarian restaurant in Winnipeg — generous prasadam thalis at remarkably affordable prices in a peaceful setting.',
        cuisineTags: ['Pure Veg', 'Indian', 'Vegetarian', 'Community'],
        cuisines: ['Indian', 'Vegetarian'],
        priceRange: '$',
        badges: ['Pure Veg', 'Budget Friendly', 'Community'],
        serviceTypes: ['Dine-in', 'Takeaway'],
        vegOnly: true,
        isVeg: true,
        rating: 4.2,
        images: [
            'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800',
            'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
            'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800',
        ],
        imageUrl: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800',
        location: { lat: 49.8778, lng: -97.1510, address: '108 Bhaktivedanta Pl, Winnipeg, MB' },
        address: '108 Bhaktivedanta Pl, Winnipeg, MB',
        hasOffer: false,
        features: ['Family Friendly', 'Community', 'Takeout'],
        opening_hours: { 'Mon-Sun': '11:30am - 7pm' },
        _isMockData: true,
    } as Restaurant,
    {
        _id: 'fr21',
        name: 'Prairie Roots Veggie Bistro',
        description: 'Saskatoon\'s farm-to-fork vegetarian bistro — celebrating Saskatchewan lentils, wild mushrooms and prairie grain bowls with genuine local pride.',
        cuisineTags: ['Vegetarian', 'Farm-to-Table', 'Canadian', 'Prairie'],
        cuisines: ['Vegetarian', 'Canadian'],
        priceRange: '$$',
        badges: ['Farm-to-Table', 'Vegetarian', 'Local Favourite'],
        serviceTypes: ['Dine-in', 'Takeaway'],
        vegOnly: true,
        isVeg: true,
        rating: 4.5,
        images: [
            'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800',
            'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
            'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800',
        ],
        imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800',
        location: { lat: 52.1332, lng: -106.6700, address: '230 20th St W, Saskatoon, SK' },
        address: '230 20th St W, Saskatoon, SK',
        hasOffer: false,
        features: ['Local Sourced', 'Seasonal Menu', 'Brunch'],
        opening_hours: { 'Wed-Mon': '11am - 9pm', 'Tue': 'Closed' },
        _isMockData: true,
    } as Restaurant,
    {
        _id: 'fr22',
        name: 'Bloom Vegetarian Cafe',
        description: 'Whitehorse\'s only fully vegetarian cafe — hearty soups, grain salads and house-made pastries using local Yukon ingredients in Canada\'s north.',
        cuisineTags: ['Vegetarian', 'Cafe', 'Canadian', 'Yukon'],
        cuisines: ['Vegetarian', 'Cafe'],
        priceRange: '$',
        badges: ['Cozy', 'Local Favourite', 'Vegetarian'],
        serviceTypes: ['Dine-in', 'Takeaway'],
        vegOnly: true,
        isVeg: true,
        rating: 4.3,
        images: [
            'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800',
            'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800',
            'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
        ],
        imageUrl: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800',
        location: { lat: 60.7212, lng: -135.0568, address: '305 Main St, Whitehorse, YT' },
        address: '305 Main St, Whitehorse, YT',
        hasOffer: false,
        features: ['Cozy', 'Brunch', 'Takeout'],
        opening_hours: { 'Mon-Sat': '8am - 5pm', 'Sun': 'Closed' },
        _isMockData: true,
    } as Restaurant,
    {
        _id: 'fr23',
        name: 'Ahimsa Vegan Bistro',
        description: 'Edmonton\'s only dedicated vegan fine dining spot — prix fixe menus using Alberta-grown organic vegetables in an intimate, elegant setting.',
        cuisineTags: ['Vegan', 'Fine Dining', 'Canadian', 'Alberta'],
        cuisines: ['Vegan', 'Fine Dining'],
        priceRange: '$$$',
        badges: ['Vegan', 'Fine Dining', 'Award Winning'],
        serviceTypes: ['Dine-in'],
        vegOnly: true,
        isVeg: true,
        rating: 4.7,
        images: [
            'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
            'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
            'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800',
        ],
        imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
        location: { lat: 53.5461, lng: -113.4938, address: '10330 82 Ave NW, Edmonton, AB' },
        address: '10330 82 Ave NW, Edmonton, AB',
        hasOffer: false,
        features: ['Fine Dining', 'Wine Pairing', 'Tasting Menu'],
        opening_hours: { 'Tue-Sat': '6pm - 10pm', 'Sun-Mon': 'Closed' },
        _isMockData: true,
    } as Restaurant,
    {
        _id: 'fr24',
        name: 'Lotus Root Chinese Vegetarian',
        description: 'Vancouver\'s authentic Chinese Buddhist vegetarian restaurant — mock meats, tofu hot pots and dim sum made entirely without animal products.',
        cuisineTags: ['Vegetarian', 'Chinese', 'Buddhist', 'Dim Sum'],
        cuisines: ['Chinese', 'Vegetarian'],
        priceRange: '$$',
        badges: ['Pure Veg', 'Authentic', 'Buddhist'],
        serviceTypes: ['Dine-in', 'Takeaway'],
        vegOnly: true,
        isVeg: true,
        rating: 4.5,
        images: [
            'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800',
            'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
            'https://images.unsplash.com/photo-1547592180-85f173990554?w=800',
        ],
        imageUrl: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800',
        location: { lat: 49.2631, lng: -123.1367, address: '455 W Broadway, Vancouver, BC' },
        address: '455 W Broadway, Vancouver, BC',
        hasOffer: true,
        offer: 'Dim sum weekend brunch $22/person',
        features: ['Dim Sum', 'Delivery', 'Group Friendly'],
        opening_hours: { 'Mon-Sun': '11am - 9:30pm' },
        _isMockData: true,
    } as Restaurant,
    {
        _id: 'fr25',
        name: 'Mosaic Vegetarian Kitchen',
        description: 'Calgary\'s globally-inspired all-vegetarian kitchen — mezze platters, shakshuka, falafel bowls and vegan desserts drawing from Mediterranean and Middle Eastern traditions.',
        cuisineTags: ['Vegetarian', 'Mediterranean', 'Middle Eastern', 'Global'],
        cuisines: ['Vegetarian', 'Mediterranean'],
        priceRange: '$$',
        badges: ['Vegetarian', 'Mediterranean', 'Popular'],
        serviceTypes: ['Dine-in', 'Takeaway'],
        vegOnly: true,
        isVeg: true,
        rating: 4.6,
        images: [
            'https://images.unsplash.com/photo-1544025162-d76694265947?w=800',
            'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
            'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800',
        ],
        imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800',
        location: { lat: 51.0430, lng: -114.0720, address: '622 11 Ave SW, Calgary, AB' },
        address: '622 11 Ave SW, Calgary, AB',
        hasOffer: false,
        features: ['Mezze', 'Outdoor Patio', 'Group Friendly'],
        opening_hours: { 'Mon-Sun': '11:30am - 9:30pm' },
        _isMockData: true,
    } as Restaurant,
    {
        _id: 'fr26',
        name: 'Maitri Vegan Indian',
        description: 'Brampton\'s beloved pure veg Indian restaurant — rich Punjabi curries, stuffed parathas and creamy lassis serving the large South Asian community.',
        cuisineTags: ['Pure Veg', 'Indian', 'Punjabi', 'Vegetarian'],
        cuisines: ['Indian', 'Vegetarian'],
        priceRange: '$',
        badges: ['Pure Veg', 'Punjabi', 'Budget Friendly'],
        serviceTypes: ['Dine-in', 'Takeaway', 'Delivery'],
        vegOnly: true,
        isVeg: true,
        rating: 4.3,
        images: [
            'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=800',
            'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800',
            'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
        ],
        imageUrl: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=800',
        location: { lat: 43.7315, lng: -79.7624, address: '8 Sunny Meadow Blvd, Brampton, ON' },
        address: '8 Sunny Meadow Blvd, Brampton, ON',
        hasOffer: true,
        offer: 'Paratha combo $10.99 all day',
        features: ['Delivery', 'Family Friendly', 'Quick Bite'],
        opening_hours: { 'Mon-Sun': '10am - 10pm' },
        _isMockData: true,
    } as Restaurant,
    {
        _id: 'fr27',
        name: 'Zucca Veggie Grill',
        description: 'Toronto\'s lively vegetarian grill bar — wood-fired veggie burgers, grilled halloumi wraps and craft kombucha on tap in the Church-Wellesley Village.',
        cuisineTags: ['Vegetarian', 'Grill', 'Burgers', 'Canadian'],
        cuisines: ['Vegetarian', 'Grill'],
        priceRange: '$$',
        badges: ['Vegetarian', 'Popular', 'Trendy'],
        serviceTypes: ['Dine-in', 'Takeaway', 'Delivery'],
        vegOnly: true,
        isVeg: true,
        rating: 4.4,
        images: [
            'https://images.unsplash.com/photo-1550547660-d9450f859349?w=800',
            'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800',
            'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800',
        ],
        imageUrl: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=800',
        location: { lat: 43.6590, lng: -79.3800, address: '612 Church St, Toronto, ON' },
        address: '612 Church St, Toronto, ON',
        hasOffer: true,
        offer: 'Burger + fries + drink $18.99',
        features: ['Bar', 'Delivery', 'Late Night'],
        opening_hours: { 'Mon-Sun': '11am - 11pm' },
        _isMockData: true,
    } as Restaurant,
    {
        _id: 'fr28',
        name: 'Terrain Veggie Bistro',
        description: 'Edmonton\'s cozy plant-based bistro — seasonal soups, jackfruit tacos and decadent vegan desserts made from Alberta-grown ingredients.',
        cuisineTags: ['Vegan', 'Healthy', 'Canadian', 'Alberta'],
        cuisines: ['Vegan', 'Canadian'],
        priceRange: '$$',
        badges: ['Vegan', 'Cozy', 'Local Favourite'],
        serviceTypes: ['Dine-in', 'Takeaway'],
        vegOnly: true,
        isVeg: true,
        rating: 4.4,
        images: [
            'https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=800',
            'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800',
            'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?w=800',
        ],
        imageUrl: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=800',
        location: { lat: 53.5444, lng: -113.4909, address: '10168 Whyte Ave, Edmonton, AB' },
        address: '10168 Whyte Ave, Edmonton, AB',
        hasOffer: false,
        features: ['Seasonal Menu', 'Takeout', 'Cozy'],
        opening_hours: { 'Tue-Sun': '11am - 9pm', 'Mon': 'Closed' },
        _isMockData: true,
    } as Restaurant,
];

// ─────────────────────────────────────────────
// ALL RESTAURANTS
// ─────────────────────────────────────────────
export const mockAllRestaurants: Restaurant[] = [
    {
        _id: 'r1',
        name: 'Virtuous Pie (Toronto)',
        description: 'Toronto outpost of the beloved Vancouver plant-based pizzeria — creative vegan pies with cashew cheese, cauliflower wings and craft soft-serve.',
        cuisineTags: ['Vegan', 'Pizza', 'Italian', 'Plant-Based'],
        cuisines: ['Vegan', 'Pizza'],
        priceRange: '$$',
        badges: ['Vegan', 'Popular'],
        serviceTypes: ['Dine-in', 'Takeaway', 'Delivery'],
        vegOnly: true,
        isVeg: true,
        rating: 4.5,
        images: [
            'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800',
            'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
            'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800',
            'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800',
            'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800',
        ],
        imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800',
        location: { lat: 43.6486, lng: -79.3897, address: '326 Adelaide St W, Toronto, ON' },
        address: '326 Adelaide St W, Toronto, ON',
        hasOffer: true,
        offer: 'Happy hour slices $5 daily 3-5pm',
        features: ['Vegan', 'Takeout', 'Late Night'],
        opening_hours: { 'Mon-Sun': '11:30am - 10pm' },
    },
    {
        _id: 'r2',
        name: 'Planta Burger',
        description: 'Toronto and Miami\'s plant-based burger concept by chef and restaurateur Steven Salm — incredible smash burgers, fries and shakes with zero animal products.',
        cuisineTags: ['Vegan', 'Burgers', 'Fast Casual', 'Plant-Based'],
        cuisines: ['Vegan', 'Burgers'],
        priceRange: '$$',
        badges: ['Vegan', 'Trendy', 'Popular'],
        serviceTypes: ['Dine-in', 'Takeaway', 'Delivery'],
        vegOnly: true,
        isVeg: true,
        rating: 4.5,
        images: [
            'https://images.unsplash.com/photo-1550547660-d9450f859349?w=800',
            'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800',
            'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?w=800',
            'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
            'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800',
        ],
        imageUrl: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=800',
        location: { lat: 43.6532, lng: -79.3813, address: '1221 Bay St, Toronto, ON' },
        address: '1221 Bay St, Toronto, ON',
        hasOffer: false,
        features: ['Late Night', 'Takeout', 'Quick Bite'],
        opening_hours: { 'Mon-Sun': '11am - 10pm' },
    },
    {
        _id: 'r3',
        name: 'LOV Montreal',
        description: 'Montreal\'s beloved plant-based restaurant — beautiful, flavour-packed dishes in a gorgeous botanical space. Certified organic and entirely plant-based.',
        cuisineTags: ['Vegan', 'Organic', 'Fine Casual', 'Montreal'],
        cuisines: ['Vegan', 'Organic'],
        priceRange: '$$$',
        badges: ['Organic', 'Beautiful Space', 'Vegan'],
        serviceTypes: ['Dine-in', 'Takeaway'],
        vegOnly: true,
        isVeg: true,
        rating: 4.7,
        images: [
            'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
            'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?w=800',
            'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800',
            'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
            'https://images.unsplash.com/photo-1547592180-85f173990554?w=800',
        ],
        imageUrl: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
        location: { lat: 45.5017, lng: -73.5799, address: '464 Rue McGill, Montreal, QC' },
        address: '464 Rue McGill, Montreal, QC',
        hasOffer: false,
        features: ['Organic', 'Wine List', 'Beautiful Decor'],
        opening_hours: { 'Mon-Sun': '11am - 10pm' },
    },
    {
        _id: 'r4',
        name: 'The Naam Restaurant',
        description: 'Vancouver\'s oldest vegetarian restaurant, open since 1968 — a Kitsilano institution serving hearty plant-based comfort food 24 hours a day.',
        cuisineTags: ['Vegetarian', 'Canadian', 'Comfort Food', 'Heritage'],
        cuisines: ['Vegetarian', 'Canadian'],
        priceRange: '$$',
        badges: ['Since 1968', 'Vancouver Legend', '24 Hours'],
        serviceTypes: ['Dine-in', 'Takeaway'],
        vegOnly: true,
        isVeg: true,
        rating: 4.3,
        images: [
            'https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=800',
            'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800',
            'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800',
            'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
            'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800',
        ],
        imageUrl: 'https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=800',
        location: { lat: 49.2653, lng: -123.1680, address: '2724 W 4th Ave, Vancouver, BC' },
        address: '2724 W 4th Ave, Vancouver, BC',
        hasOffer: false,
        features: ['24 Hours', 'Patio', 'Heritage'],
        opening_hours: { 'Daily': 'Open 24 hours' },
    },
    {
        _id: 'r5',
        name: 'Cafe Bistro VegOut',
        description: 'Calgary\'s friendly neighbourhood vegan cafe — housemade soups, stuffed sandwiches and the best vegan cinnamon rolls in Alberta.',
        cuisineTags: ['Vegan', 'Cafe', 'Sandwiches', 'Baked Goods'],
        cuisines: ['Vegan', 'Cafe'],
        priceRange: '$',
        badges: ['Cozy', 'Vegan', 'Local Favourite'],
        serviceTypes: ['Dine-in', 'Takeaway'],
        vegOnly: true,
        isVeg: true,
        rating: 4.4,
        images: [
            'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800',
            'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800',
            'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800',
            'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
            'https://images.unsplash.com/photo-1547592180-85f173990554?w=800',
        ],
        imageUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800',
        location: { lat: 51.0447, lng: -114.0888, address: '1212 17 Ave SW, Calgary, AB' },
        address: '1212 17 Ave SW, Calgary, AB',
        hasOffer: true,
        offer: 'Brunch menu Sat & Sun — coffee included',
        features: ['Brunch', 'Baked Goods', 'Takeout'],
        opening_hours: { 'Mon-Sat': '8am - 6pm', 'Sun': '9am - 5pm' },
    },
    {
        _id: 'r6',
        name: 'Heartwood Vegetarian Cafe',
        description: 'Halifax\'s cherished vegetarian cafe on Agricola Street — warm soups, creative sandwiches and wholesome salads made with Nova Scotia ingredients.',
        cuisineTags: ['Vegetarian', 'Cafe', 'Nova Scotia', 'Healthy'],
        cuisines: ['Vegetarian', 'Cafe'],
        priceRange: '$',
        badges: ['Halifax Gem', 'Cozy', 'Local'],
        serviceTypes: ['Dine-in', 'Takeaway'],
        vegOnly: true,
        isVeg: true,
        rating: 4.5,
        images: [
            'https://images.unsplash.com/photo-1493857671505-72967e2e2760?w=800',
            'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800',
            'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800',
            'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
            'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800',
        ],
        imageUrl: 'https://images.unsplash.com/photo-1493857671505-72967e2e2760?w=800',
        location: { lat: 44.6521, lng: -63.5899, address: '6250 Quinpool Rd, Halifax, NS' },
        address: '6250 Quinpool Rd, Halifax, NS',
        hasOffer: false,
        features: ['Cozy', 'Soup of the Day', 'Takeout'],
        opening_hours: { 'Mon-Sat': '9am - 6pm', 'Sun': 'Closed' },
    },
    {
        _id: 'r7',
        name: 'Boxwood Cafe',
        description: 'Ottawa\'s plant-forward cafe inside the National Arts Centre — organic, locally sourced dishes that celebrate the best of the Ottawa Valley.',
        cuisineTags: ['Vegetarian', 'Organic', 'Canadian', 'Cafe'],
        cuisines: ['Vegetarian', 'Organic'],
        priceRange: '$$',
        badges: ['Organic', 'Arts Scene', 'Ottawa'],
        serviceTypes: ['Dine-in', 'Takeaway'],
        vegOnly: true,
        isVeg: true,
        rating: 4.4,
        images: [
            'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800',
            'https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=800',
            'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800',
            'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
            'https://images.unsplash.com/photo-1547592180-85f173990554?w=800',
        ],
        imageUrl: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800',
        location: { lat: 45.4236, lng: -75.6944, address: '1 Elgin St, Ottawa, ON' },
        address: '1 Elgin St, Ottawa, ON',
        hasOffer: true,
        offer: 'Lunch combos from $14',
        features: ['Organic', 'Arts Venue', 'Patio'],
        opening_hours: { 'Mon-Sun': '8am - 8pm' },
    },
    {
        _id: 'r8',
        name: 'Cafe Diem Winnipeg',
        description: 'Winnipeg\'s beloved vegetarian-friendly cafe in the Exchange District — house-baked goods, hearty soups and excellent coffee with local art on the walls.',
        cuisineTags: ['Vegetarian', 'Cafe', 'Baked Goods', 'Manitoba'],
        cuisines: ['Vegetarian', 'Cafe'],
        priceRange: '$',
        badges: ['Cozy', 'Local Art', 'Winnipeg'],
        serviceTypes: ['Dine-in', 'Takeaway'],
        vegOnly: true,
        isVeg: true,
        rating: 4.3,
        images: [
            'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800',
            'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800',
            'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800',
            'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
            'https://images.unsplash.com/photo-1465014925804-7b9ede58d0d7?w=800',
        ],
        imageUrl: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800',
        location: { lat: 49.8985, lng: -97.1403, address: '259 Portage Ave, Winnipeg, MB' },
        address: '259 Portage Ave, Winnipeg, MB',
        hasOffer: true,
        offer: 'Free muffin with coffee before 9am',
        features: ['Local Art', 'Cozy', 'Quick Bite'],
        opening_hours: { 'Mon-Fri': '7am - 6pm', 'Sat-Sun': '8am - 5pm' },
    },
    {
        _id: 'r9',
        name: 'Be Love Restaurant',
        description: 'Victoria\'s celebrated plant-based restaurant on Fort Street — seasonal menus with Vancouver Island produce, exceptional natural wines and a warm community spirit.',
        cuisineTags: ['Vegan', 'Seasonal', 'West Coast', 'Fine Casual'],
        cuisines: ['Vegan', 'Seasonal'],
        priceRange: '$$$',
        badges: ['Vegan', 'Award Winning', 'Victoria Icon'],
        serviceTypes: ['Dine-in'],
        vegOnly: true,
        isVeg: true,
        rating: 4.7,
        images: [
            'https://images.unsplash.com/photo-1543362906-acfc16c67564?w=800',
            'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800',
            'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
            'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800',
            'https://images.unsplash.com/photo-1547592180-85f173990554?w=800',
        ],
        imageUrl: 'https://images.unsplash.com/photo-1543362906-acfc16c67564?w=800',
        location: { lat: 48.4284, lng: -123.3601, address: '1019 Blanshard St, Victoria, BC' },
        address: '1019 Blanshard St, Victoria, BC',
        hasOffer: false,
        features: ['Natural Wine', 'Seasonal Menu', 'Community'],
        opening_hours: { 'Tue-Sun': '5pm - 10pm', 'Mon': 'Closed' },
    },
    {
        _id: 'r10',
        name: 'Segovia Veg Tapas',
        description: 'Winnipeg\'s top plant-based Spanish tapas bar — creative small plates, sangria and a buzzy Exchange District atmosphere that draws a loyal crowd.',
        cuisineTags: ['Vegetarian', 'Spanish', 'Tapas', 'Mediterranean'],
        cuisines: ['Vegetarian', 'Spanish'],
        priceRange: '$$',
        badges: ['Popular', 'Tapas', 'Vegetarian'],
        serviceTypes: ['Dine-in'],
        vegOnly: true,
        isVeg: true,
        rating: 4.5,
        images: [
            'https://images.unsplash.com/photo-1544025162-d76694265947?w=800',
            'https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=800',
            'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
            'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800',
            'https://images.unsplash.com/photo-1465014925804-7b9ede58d0d7?w=800',
        ],
        imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800',
        location: { lat: 49.8958, lng: -97.1391, address: '484 McGregor St, Winnipeg, MB' },
        address: '484 McGregor St, Winnipeg, MB',
        hasOffer: true,
        offer: 'Half price tapas 5-6pm daily',
        features: ['Cocktail Bar', 'Sangria', 'Late Night'],
        opening_hours: { 'Tue-Sun': '5pm - 12am', 'Mon': 'Closed' },
    },
    {
        _id: 'r11',
        name: 'Rawlicious Toronto',
        description: 'Toronto\'s raw vegan cafe — cold-pressed juices, raw tacos, live-food desserts and superfood smoothie bowls for the health-conscious diner.',
        cuisineTags: ['Vegan', 'Raw Food', 'Healthy', 'Juice Bar'],
        cuisines: ['Vegan', 'Raw Food'],
        priceRange: '$$',
        badges: ['Raw Vegan', 'Healthy', 'Juice Bar'],
        serviceTypes: ['Dine-in', 'Takeaway'],
        vegOnly: true,
        isVeg: true,
        rating: 4.3,
        images: [
            'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800',
            'https://images.unsplash.com/photo-1543362906-acfc16c67564?w=800',
            'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
        ],
        imageUrl: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800',
        location: { lat: 43.6741, lng: -79.3980, address: '1075 Yonge St, Toronto, ON' },
        address: '1075 Yonge St, Toronto, ON',
        hasOffer: false,
        features: ['Juice Bar', 'Raw Food', 'Takeout'],
        opening_hours: { 'Mon-Sun': '9am - 8pm' },
    },
    {
        _id: 'r12',
        name: 'Chickpea Vancouver',
        description: 'Bright, welcoming vegan street food restaurant in Vancouver — shawarma, falafel wraps and mezze bowls inspired by the Middle East and the Mediterranean.',
        cuisineTags: ['Vegan', 'Middle Eastern', 'Falafel', 'Street Food'],
        cuisines: ['Vegan', 'Middle Eastern'],
        priceRange: '$',
        badges: ['Vegan', 'Street Food', 'Popular'],
        serviceTypes: ['Dine-in', 'Takeaway', 'Delivery'],
        vegOnly: true,
        isVeg: true,
        rating: 4.5,
        images: [
            'https://images.unsplash.com/photo-1465014925804-7b9ede58d0d7?w=800',
            'https://images.unsplash.com/photo-1544025162-d76694265947?w=800',
            'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
        ],
        imageUrl: 'https://images.unsplash.com/photo-1465014925804-7b9ede58d0d7?w=800',
        location: { lat: 49.2802, lng: -123.1100, address: '4298 Main St, Vancouver, BC' },
        address: '4298 Main St, Vancouver, BC',
        hasOffer: true,
        offer: 'Combo meal $13.99 daily',
        features: ['Quick Bite', 'Takeout', 'Delivery'],
        opening_hours: { 'Mon-Sun': '11am - 9pm' },
    },
    {
        _id: 'r13',
        name: 'Cafe Mosaics Edmonton',
        description: 'Edmonton\'s long-running vegetarian restaurant on Whyte Ave — eclectic global dishes, house-made veggie burgers and a warm, inclusive atmosphere since 1993.',
        cuisineTags: ['Vegetarian', 'Global', 'Canadian', 'Heritage'],
        cuisines: ['Vegetarian', 'Global'],
        priceRange: '$$',
        badges: ['Edmonton Icon', 'Since 1993', 'Vegetarian'],
        serviceTypes: ['Dine-in', 'Takeaway'],
        vegOnly: true,
        isVeg: true,
        rating: 4.4,
        images: [
            'https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=800',
            'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800',
            'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
        ],
        imageUrl: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=800',
        location: { lat: 53.5228, lng: -113.5007, address: '10844 82 Ave NW, Edmonton, AB' },
        address: '10844 82 Ave NW, Edmonton, AB',
        hasOffer: true,
        offer: 'All-you-can-eat brunch $18 weekends',
        features: ['Brunch', 'Heritage', 'Group Friendly'],
        opening_hours: { 'Mon-Sun': '9am - 9pm' },
    },
    {
        _id: 'r14',
        name: 'Ital Vital Montreal',
        description: 'Montreal\'s Rastafarian-inspired ital vegan restaurant — natural, organic, salt-free Caribbean cooking celebrating life and clean eating in Mile End.',
        cuisineTags: ['Vegan', 'Caribbean', 'Ital', 'Organic'],
        cuisines: ['Vegan', 'Caribbean'],
        priceRange: '$$',
        badges: ['Vegan', 'Unique', 'Organic'],
        serviceTypes: ['Dine-in', 'Takeaway'],
        vegOnly: true,
        isVeg: true,
        rating: 4.4,
        images: [
            'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=800',
            'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800',
            'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
        ],
        imageUrl: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=800',
        location: { lat: 45.5235, lng: -73.5900, address: '5228 Blvd St-Laurent, Montreal, QC' },
        address: '5228 Blvd St-Laurent, Montreal, QC',
        hasOffer: false,
        features: ['Organic', 'Caribbean', 'Unique Experience'],
        opening_hours: { 'Tue-Sun': '11am - 8pm', 'Mon': 'Closed' },
    },
    {
        _id: 'r15',
        name: 'Nourish Kitchen Victoria',
        description: 'Victoria BC plant-based restaurant committed to zero waste — creative vegan bowls and cold-pressed juices using Vancouver Island produce with minimal packaging.',
        cuisineTags: ['Vegan', 'Zero Waste', 'Healthy', 'BC'],
        cuisines: ['Vegan', 'Healthy'],
        priceRange: '$$',
        badges: ['Zero Waste', 'Healthy', 'Eco-Friendly'],
        serviceTypes: ['Dine-in', 'Takeaway'],
        vegOnly: true,
        isVeg: true,
        rating: 4.6,
        images: [
            'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800',
            'https://images.unsplash.com/photo-1543362906-acfc16c67564?w=800',
            'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
        ],
        imageUrl: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800',
        location: { lat: 48.4284, lng: -123.3656, address: '225 Quebec St, Victoria, BC' },
        address: '225 Quebec St, Victoria, BC',
        hasOffer: false,
        features: ['Juice Bar', 'Zero Waste', 'Outdoor Seating'],
        opening_hours: { 'Mon-Sat': '9am - 8pm', 'Sun': '10am - 6pm' },
    },
    {
        _id: 'r16',
        name: 'Sweet Lemon Cafe',
        description: 'Saskatoon\'s charming all-day vegetarian cafe — house-baked quiches, grain bowls and organic fair-trade coffee in a sunlit Riversdale setting.',
        cuisineTags: ['Vegetarian', 'Cafe', 'Saskatchewan', 'Brunch'],
        cuisines: ['Vegetarian', 'Cafe'],
        priceRange: '$',
        badges: ['Cozy', 'Brunch Spot', 'Local'],
        serviceTypes: ['Dine-in', 'Takeaway'],
        vegOnly: true,
        isVeg: true,
        rating: 4.3,
        images: [
            'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800',
            'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800',
            'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
        ],
        imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800',
        location: { lat: 52.1199, lng: -106.6805, address: '710 20th St W, Saskatoon, SK' },
        address: '710 20th St W, Saskatoon, SK',
        hasOffer: true,
        offer: 'Quiche + salad + coffee $14.99',
        features: ['Brunch', 'Organic Coffee', 'Takeout'],
        opening_hours: { 'Mon-Sat': '8am - 5pm', 'Sun': '9am - 4pm' },
    },
    {
        _id: 'r17',
        name: 'Ahimsa Vegan Bistro',
        description: 'Edmonton\'s only dedicated vegan fine dining spot — prix fixe menus using Alberta-grown organic vegetables in an intimate, elegant setting.',
        cuisineTags: ['Vegan', 'Fine Dining', 'Canadian', 'Alberta'],
        cuisines: ['Vegan', 'Fine Dining'],
        priceRange: '$$$',
        badges: ['Vegan', 'Fine Dining', 'Award Winning'],
        serviceTypes: ['Dine-in'],
        vegOnly: true,
        isVeg: true,
        rating: 4.7,
        images: [
            'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
            'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800',
            'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
        ],
        imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
        location: { lat: 53.5461, lng: -113.4938, address: '10330 82 Ave NW, Edmonton, AB' },
        address: '10330 82 Ave NW, Edmonton, AB',
        hasOffer: false,
        features: ['Fine Dining', 'Wine Pairing', 'Tasting Menu'],
        opening_hours: { 'Tue-Sat': '6pm - 10pm', 'Sun-Mon': 'Closed' },
        _isMockData: true,
    } as Restaurant,
    {
        _id: 'r18',
        name: 'Lotus Root Chinese Vegetarian',
        description: 'Vancouver\'s authentic Chinese Buddhist vegetarian restaurant — mock meats, tofu hot pots and dim sum made entirely without animal products.',
        cuisineTags: ['Vegetarian', 'Chinese', 'Buddhist', 'Dim Sum'],
        cuisines: ['Chinese', 'Vegetarian'],
        priceRange: '$$',
        badges: ['Pure Veg', 'Authentic', 'Buddhist'],
        serviceTypes: ['Dine-in', 'Takeaway'],
        vegOnly: true,
        isVeg: true,
        rating: 4.5,
        images: [
            'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800',
            'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?w=800',
            'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
        ],
        imageUrl: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800',
        location: { lat: 49.2631, lng: -123.1367, address: '455 W Broadway, Vancouver, BC' },
        address: '455 W Broadway, Vancouver, BC',
        hasOffer: true,
        offer: 'Dim sum weekend brunch $22/person',
        features: ['Dim Sum', 'Delivery', 'Group Friendly'],
        opening_hours: { 'Mon-Sun': '11am - 9:30pm' },
        _isMockData: true,
    } as Restaurant,
    {
        _id: 'r19',
        name: 'Zucca Veggie Grill',
        description: 'Toronto\'s lively vegetarian grill bar — wood-fired veggie burgers, grilled halloumi wraps and craft kombucha on tap in the Church-Wellesley Village.',
        cuisineTags: ['Vegetarian', 'Grill', 'Burgers', 'Canadian'],
        cuisines: ['Vegetarian', 'Grill'],
        priceRange: '$$',
        badges: ['Vegetarian', 'Popular', 'Trendy'],
        serviceTypes: ['Dine-in', 'Takeaway', 'Delivery'],
        vegOnly: true,
        isVeg: true,
        rating: 4.4,
        images: [
            'https://images.unsplash.com/photo-1550547660-d9450f859349?w=800',
            'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800',
            'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
        ],
        imageUrl: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=800',
        location: { lat: 43.6590, lng: -79.3800, address: '612 Church St, Toronto, ON' },
        address: '612 Church St, Toronto, ON',
        hasOffer: true,
        offer: 'Burger + fries + drink $18.99',
        features: ['Bar', 'Delivery', 'Late Night'],
        opening_hours: { 'Mon-Sun': '11am - 11pm' },
        _isMockData: true,
    } as Restaurant,
    {
        _id: 'r20',
        name: 'Maitri Vegan Indian',
        description: 'Brampton\'s beloved pure veg Indian restaurant — rich Punjabi curries, stuffed parathas and creamy lassis serving the large South Asian community.',
        cuisineTags: ['Pure Veg', 'Indian', 'Punjabi', 'Vegetarian'],
        cuisines: ['Indian', 'Vegetarian'],
        priceRange: '$',
        badges: ['Pure Veg', 'Punjabi', 'Budget Friendly'],
        serviceTypes: ['Dine-in', 'Takeaway', 'Delivery'],
        vegOnly: true,
        isVeg: true,
        rating: 4.3,
        images: [
            'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=800',
            'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800',
            'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800',
        ],
        imageUrl: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=800',
        location: { lat: 43.7315, lng: -79.7624, address: '8 Sunny Meadow Blvd, Brampton, ON' },
        address: '8 Sunny Meadow Blvd, Brampton, ON',
        hasOffer: true,
        offer: 'Paratha combo $10.99 all day',
        features: ['Delivery', 'Family Friendly', 'Quick Bite'],
        opening_hours: { 'Mon-Sun': '10am - 10pm' },
        _isMockData: true,
    } as Restaurant,
    {
        _id: 'r21',
        name: 'Mosaic Vegetarian Kitchen',
        description: 'Calgary\'s globally-inspired all-vegetarian kitchen — mezze platters, shakshuka, falafel bowls and vegan desserts drawing from Mediterranean traditions.',
        cuisineTags: ['Vegetarian', 'Mediterranean', 'Middle Eastern', 'Global'],
        cuisines: ['Vegetarian', 'Mediterranean'],
        priceRange: '$$',
        badges: ['Vegetarian', 'Mediterranean', 'Popular'],
        serviceTypes: ['Dine-in', 'Takeaway'],
        vegOnly: true,
        isVeg: true,
        rating: 4.6,
        images: [
            'https://images.unsplash.com/photo-1544025162-d76694265947?w=800',
            'https://images.unsplash.com/photo-1465014925804-7b9ede58d0d7?w=800',
            'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
        ],
        imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800',
        location: { lat: 51.0430, lng: -114.0720, address: '622 11 Ave SW, Calgary, AB' },
        address: '622 11 Ave SW, Calgary, AB',
        hasOffer: false,
        features: ['Mezze', 'Outdoor Patio', 'Group Friendly'],
        opening_hours: { 'Mon-Sun': '11:30am - 9:30pm' },
        _isMockData: true,
    } as Restaurant,
];

// ─────────────────────────────────────────────
// DETAIL DATA
// ─────────────────────────────────────────────
export const mockRestaurantDetails: Record<string, RestaurantDetail> = {
    fr1: {
        ...mockFeaturedRestaurants[0],
        menuSections: [
            {
                title: 'Small Plates',
                items: [
                    { name: 'Roasted Beet Tartare', description: 'Cashew cream, pickled mustard seeds, micro herbs', price: 22 },
                    { name: 'Smoked Carrot Bisque', description: 'Coconut cream, chive oil, toasted seeds', price: 18 },
                    { name: 'Crispy Polenta Cake', description: 'Wild mushroom ragù, fresh thyme, aged cashew parmesan', price: 19 },
                ],
            },
            {
                title: 'Mains',
                items: [
                    { name: 'Wild Mushroom Risotto', description: 'BC chanterelles, truffle, aged cashew parmesan', price: 36 },
                    { name: 'Jackfruit Wellington', description: 'Mushroom duxelles, puff pastry, red wine jus', price: 42 },
                    { name: 'Seared Cauliflower Steak', description: 'Romesco, charred broccolini, crispy capers', price: 34 },
                ],
            },
            {
                title: 'Desserts',
                items: [
                    { name: 'Dark Chocolate Ganache', description: 'Raspberry coulis, candied hazelnuts', price: 16 },
                    { name: 'Lemon Tart', description: 'Cashew curd, blueberry compote, shortbread', price: 14 },
                ],
            },
        ],
        contact: { phone: '+1-604-566-9001', email: 'hello@theacornrestaurant.ca' },
        openingHours: ['Tue-Sun: 5pm - 10pm', 'Mon: Closed'],
    },
    fr2: {
        ...mockFeaturedRestaurants[1],
        menuSections: [
            {
                title: 'Bowls',
                items: [
                    { name: 'Dragon Bowl', description: 'Brown rice, beets, carrots, tahini dressing', price: 18 },
                    { name: 'Macro Bowl', description: 'Quinoa, roasted veggies, miso gravy', price: 17 },
                    { name: 'Green Goddess Bowl', description: 'Kale, avocado, edamame, sesame', price: 19 },
                ],
            },
            {
                title: 'Smoothies',
                items: [
                    { name: 'Green Machine', description: 'Spinach, banana, mango, coconut water', price: 9 },
                    { name: 'Berry Blast', description: 'Mixed berries, almond milk, chia seeds', price: 9 },
                ],
            },
        ],
        contact: { phone: '+1-416-599-4442', email: 'hello@freshrestaurants.ca' },
        openingHours: ['Mon-Sun: 9am - 10pm'],
    },
    fr4: {
        ...mockFeaturedRestaurants[3],
        menuSections: [
            {
                title: 'Small Plates',
                items: [
                    { name: 'Vegan Char Siu Bao', description: 'BBQ jackfruit, steamed bun, pickled cucumber', price: 16 },
                    { name: 'Miso Ramen', description: 'Rich miso broth, crispy tofu, nori, bamboo shoots', price: 22 },
                    { name: 'Truffle Edamame Dumplings', description: 'Pan-fried, yuzu dipping sauce', price: 18 },
                ],
            },
            {
                title: 'Mains',
                items: [
                    { name: 'Spicy Tuna Roll (vegan)', description: 'Watermelon tuna, avocado, sriracha aioli', price: 19 },
                    { name: 'Pho Bo (vegan)', description: 'Rich mushroom broth, rice noodles, bean sprouts', price: 21 },
                ],
            },
        ],
        contact: { phone: '+1-416-916-1600', email: 'queen@plantaqueen.com' },
        openingHours: ['Mon-Sun: 12pm - 11pm'],
    },
    fr6: {
        ...mockFeaturedRestaurants[5],
        menuSections: [
            {
                title: 'Thali & Mains',
                items: [
                    { name: 'Unlimited Thali', description: 'Dal, sabzi, rice, roti, pickle, papad', price: 15 },
                    { name: 'Paneer Butter Masala', description: 'Creamy tomato gravy, fresh paneer, naan', price: 16 },
                    { name: 'Dal Makhani', description: 'Slow-cooked black lentils, cream, butter naan', price: 14 },
                ],
            },
            {
                title: 'Breads & Sides',
                items: [
                    { name: 'Stuffed Paratha', description: 'Aloo or paneer stuffed, served with curd', price: 9 },
                    { name: 'Mango Lassi', description: 'Thick yogurt, Alphonso mango, cardamom', price: 6 },
                ],
            },
        ],
        contact: { phone: '+1-403-555-0198', email: 'info@vedgebistro.ca' },
        openingHours: ['Mon-Sun: 11am - 10pm'],
    },
    r1: {
        ...mockAllRestaurants[0],
        menuSections: [
            {
                title: 'Pizzas',
                items: [
                    { name: 'Funghi Truffle', description: 'Cashew mozzarella, wild mushrooms, truffle oil', price: 24 },
                    { name: 'Margherita', description: 'San Marzano, cashew mozzarella, fresh basil', price: 19 },
                    { name: 'Smoky BBQ', description: 'BBQ jackfruit, caramelised onion, cashew ranch', price: 22 },
                ],
            },
            {
                title: 'Sides',
                items: [
                    { name: 'Cauliflower Wings', description: 'Buffalo or honey-garlic, ranch dipping sauce', price: 14 },
                    { name: 'Soft Serve', description: 'Rotating flavours, house-made cones', price: 6 },
                ],
            },
        ],
        contact: { phone: '+1-416-792-9433', email: 'toronto@virtuouspie.com' },
        openingHours: 'Mon-Sun: 11:30am - 10pm',
    },
    r3: {
        ...mockAllRestaurants[2],
        menuSections: [
            {
                title: 'Starters',
                items: [
                    { name: 'Roasted Cauliflower', description: 'Chermoula, preserved lemon, toasted almonds', price: 18 },
                    { name: 'Chilled Beet Soup', description: 'Cucumber, dill oil, cashew cream', price: 16 },
                ],
            },
            {
                title: 'Mains',
                items: [
                    { name: 'Smoked Portobello', description: 'Herb crust, root vegetable gratin, red wine jus', price: 38 },
                    { name: 'Saffron Risotto', description: 'Roasted fennel, gremolata, cashew parmesan', price: 34 },
                    { name: 'Mushroom Bourguignon', description: 'Sourdough, mashed potatoes, herb oil', price: 36 },
                ],
            },
        ],
        contact: { phone: '+1-514-287-9158', email: 'bonjour@lovmtl.com' },
        openingHours: ['Mon-Sun: 11am - 10pm'],
    },
};

// ─────────────────────────────────────────────
// COMBINED EXPORTS
// ─────────────────────────────────────────────
export const mockRestaurants: Restaurant[] = [
    ...mockFeaturedRestaurants,
    ...mockAllRestaurants,
];

export const mockEvents = mockRestaurants as any[];